<div class="footer">
    <p class="footer-href">友情链接：<a href="#">中国石化 |</a><a href="#">中国石油化工集团公司 |</a><a href="#">中国石油化工股份有限公司 |</a><a href="#">中国石化新闻网 |</a>
        <a href="#">石化盈科 |</a> <a href="#">大亚湾物流公共信息平台 |</a><a href="#">中国机械工业联合会机经网</a></p>
    <p class="footer-href">
        ©2011-2016 长城电商 商机惠 版权所有 未经允许请勿转载 京ICP备13046076号 京公网安备110401400065
    </p>
    <p class="footer-href">
        技术支持：北京长城电子商务有限公司 Email:egwservice@egreatwall.com
    </p>
</div>