	<div id="top"></div>
	<div id="navigator">
       	<table class="layerTable">
           	<tr>
               	<td class="tleft"></td>
                	<td class="tcenter">
						<div class="contleft">http://ec.sinopec.com/</div>
                   		<div class="contpanel">
                   			<a href="http://mall.easy-pec.com/ecmall/" target="_blank">易派客</a>
                       		<a href="http://www.sinopecgroup.com/" target="_blank">中国石化集团公司网站</a>
                       		<a href="http://www.sinopec.com/" target="_blank">中国石化股份分公司网站</a>
                       		<a href="http://www.intl.sinopec.com/" target="_blank">中国石化国际事业公司网站</a>
                       	</div>
                   </td>
                   <td class="tright"></td>
               </tr>
		</table>
	</div>