package com.bizwink.cms.sjswsbs;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Letter implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LETTER.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LETTER.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LETTER.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LETTER.FILEUPLOAD
     *
     * @mbggenerated
     */
    private String fileupload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LETTER.DEPTID
     *
     * @mbggenerated
     */
    private BigDecimal deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LETTER.CATEGORYCODE
     *
     * @mbggenerated
     */
    private BigDecimal categorycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LETTER.PUBLISHFLAG
     *
     * @mbggenerated
     */
    private BigDecimal publishflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LETTER.CREATEDATE
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LETTER.REPLYCONTENT
     *
     * @mbggenerated
     */
    private String replycontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LETTER.REPLYTIME
     *
     * @mbggenerated
     */
    private Date replytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LETTER.STATUSFLAG
     *
     * @mbggenerated
     */
    private BigDecimal statusflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LETTER.SELECTEDFLAG
     *
     * @mbggenerated
     */
    private BigDecimal selectedflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LETTER.NEWFLAG
     *
     * @mbggenerated
     */
    private BigDecimal newflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LETTER.SEARCHMSG
     *
     * @mbggenerated
     */
    private String searchmsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LETTER.ID
     *
     * @return the value of TBL_LETTER.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LETTER.ID
     *
     * @param id the value for TBL_LETTER.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LETTER.TITLE
     *
     * @return the value of TBL_LETTER.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LETTER.TITLE
     *
     * @param title the value for TBL_LETTER.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LETTER.CONTENT
     *
     * @return the value of TBL_LETTER.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LETTER.CONTENT
     *
     * @param content the value for TBL_LETTER.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LETTER.FILEUPLOAD
     *
     * @return the value of TBL_LETTER.FILEUPLOAD
     *
     * @mbggenerated
     */
    public String getFileupload() {
        return fileupload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LETTER.FILEUPLOAD
     *
     * @param fileupload the value for TBL_LETTER.FILEUPLOAD
     *
     * @mbggenerated
     */
    public void setFileupload(String fileupload) {
        this.fileupload = fileupload == null ? null : fileupload.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LETTER.DEPTID
     *
     * @return the value of TBL_LETTER.DEPTID
     *
     * @mbggenerated
     */
    public BigDecimal getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LETTER.DEPTID
     *
     * @param deptid the value for TBL_LETTER.DEPTID
     *
     * @mbggenerated
     */
    public void setDeptid(BigDecimal deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LETTER.CATEGORYCODE
     *
     * @return the value of TBL_LETTER.CATEGORYCODE
     *
     * @mbggenerated
     */
    public BigDecimal getCategorycode() {
        return categorycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LETTER.CATEGORYCODE
     *
     * @param categorycode the value for TBL_LETTER.CATEGORYCODE
     *
     * @mbggenerated
     */
    public void setCategorycode(BigDecimal categorycode) {
        this.categorycode = categorycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LETTER.PUBLISHFLAG
     *
     * @return the value of TBL_LETTER.PUBLISHFLAG
     *
     * @mbggenerated
     */
    public BigDecimal getPublishflag() {
        return publishflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LETTER.PUBLISHFLAG
     *
     * @param publishflag the value for TBL_LETTER.PUBLISHFLAG
     *
     * @mbggenerated
     */
    public void setPublishflag(BigDecimal publishflag) {
        this.publishflag = publishflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LETTER.CREATEDATE
     *
     * @return the value of TBL_LETTER.CREATEDATE
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LETTER.CREATEDATE
     *
     * @param createdate the value for TBL_LETTER.CREATEDATE
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LETTER.REPLYCONTENT
     *
     * @return the value of TBL_LETTER.REPLYCONTENT
     *
     * @mbggenerated
     */
    public String getReplycontent() {
        return replycontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LETTER.REPLYCONTENT
     *
     * @param replycontent the value for TBL_LETTER.REPLYCONTENT
     *
     * @mbggenerated
     */
    public void setReplycontent(String replycontent) {
        this.replycontent = replycontent == null ? null : replycontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LETTER.REPLYTIME
     *
     * @return the value of TBL_LETTER.REPLYTIME
     *
     * @mbggenerated
     */
    public Date getReplytime() {
        return replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LETTER.REPLYTIME
     *
     * @param replytime the value for TBL_LETTER.REPLYTIME
     *
     * @mbggenerated
     */
    public void setReplytime(Date replytime) {
        this.replytime = replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LETTER.STATUSFLAG
     *
     * @return the value of TBL_LETTER.STATUSFLAG
     *
     * @mbggenerated
     */
    public BigDecimal getStatusflag() {
        return statusflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LETTER.STATUSFLAG
     *
     * @param statusflag the value for TBL_LETTER.STATUSFLAG
     *
     * @mbggenerated
     */
    public void setStatusflag(BigDecimal statusflag) {
        this.statusflag = statusflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LETTER.SELECTEDFLAG
     *
     * @return the value of TBL_LETTER.SELECTEDFLAG
     *
     * @mbggenerated
     */
    public BigDecimal getSelectedflag() {
        return selectedflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LETTER.SELECTEDFLAG
     *
     * @param selectedflag the value for TBL_LETTER.SELECTEDFLAG
     *
     * @mbggenerated
     */
    public void setSelectedflag(BigDecimal selectedflag) {
        this.selectedflag = selectedflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LETTER.NEWFLAG
     *
     * @return the value of TBL_LETTER.NEWFLAG
     *
     * @mbggenerated
     */
    public BigDecimal getNewflag() {
        return newflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LETTER.NEWFLAG
     *
     * @param newflag the value for TBL_LETTER.NEWFLAG
     *
     * @mbggenerated
     */
    public void setNewflag(BigDecimal newflag) {
        this.newflag = newflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LETTER.SEARCHMSG
     *
     * @return the value of TBL_LETTER.SEARCHMSG
     *
     * @mbggenerated
     */
    public String getSearchmsg() {
        return searchmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LETTER.SEARCHMSG
     *
     * @param searchmsg the value for TBL_LETTER.SEARCHMSG
     *
     * @mbggenerated
     */
    public void setSearchmsg(String searchmsg) {
        this.searchmsg = searchmsg == null ? null : searchmsg.trim();
    }


    private String cname;
    private String typename;

    private String editor;
    private String linkman;
    private String phone;

    private String department;
    private String oldcode;

    public String getCname() {
        return cname;
    }

    public void setCname(String cname) {
        this.cname = cname;
    }

    public String getTypename() {
        return typename;
    }

    public void setTypename(String typename) {
        this.typename = typename;
    }

    public String getEditor() {
        return editor;
    }

    public void setEditor(String editor) {
        this.editor = editor;
    }

    public String getLinkman() {
        return linkman;
    }

    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public String getOldcode() {
        return oldcode;
    }

    public void setOldcode(String oldcode) {
        this.oldcode = oldcode;
    }
}