package com.bizwink.persistence;

import com.bizwink.po.ArticleClass;
import com.bizwink.po.ArticleClassExample;
import com.bizwink.vo.TrainMajor;
import com.bizwink.vo.TrainMajorCourse;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

public interface ArticleClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ARTICLE_CLASS
     *
     * @mbggenerated
     */
    int countByExample(ArticleClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ARTICLE_CLASS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ARTICLE_CLASS
     *
     * @mbggenerated
     */
    int insert(ArticleClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ARTICLE_CLASS
     *
     * @mbggenerated
     */
    int insertSelective(ArticleClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ARTICLE_CLASS
     *
     * @mbggenerated
     */
    ArticleClass selectByPrimaryKey(BigDecimal ID);

    List<ArticleClass> getTrainCources(BigDecimal articleid);

    List<TrainMajor> getMajors(Map params);

    List<TrainMajorCourse> getCources(Map params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ARTICLE_CLASS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArticleClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ARTICLE_CLASS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticleClass record);
}