package com.bizwink.persistence;

import com.bizwink.po.ChangeNotice;
import com.bizwink.po.ChangeNoticeExample;
import com.bizwink.po.ChangeNoticeWithBLOBs;
import com.bizwink.vo.voChangeNotice;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;
import java.util.Map;

public interface ChangeNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    int countByExample(ChangeNoticeExample example);

    BigDecimal getChangeNoticeCount(Timestamp now);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    int insert(ChangeNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    int insertSelective(ChangeNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    ChangeNoticeWithBLOBs selectByPrimaryKey(String uuid);

    List<voChangeNotice> getChangeNoticeList(Map params);

    List<voChangeNotice> getTopChangeNotice(Map params);

    List<voChangeNotice> SearchChangeNoticeList(Map params);

    BigDecimal SearchChangeNoticeCount(Map params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChangeNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ChangeNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChangeNotice record);
}