package com.bizwink.persistence;

import com.bizwink.po.CmsTemplate;
import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

public interface CmsTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_TEMPLATE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_TEMPLATE
     *
     * @mbggenerated
     */
    int insert(CmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_TEMPLATE
     *
     * @mbggenerated
     */
    int insertSelective(CmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_TEMPLATE
     *
     * @mbggenerated
     */
    CmsTemplate selectByPrimaryKey(BigDecimal ID);

    List<CmsTemplate> selectBySiteID(BigDecimal siteid);

    List<CmsTemplate> selectPublishTemplate(Map params);

    List<CmsTemplate> getTemplateByColumnid(Map params);

    CmsTemplate getTemplate(CmsTemplate cmsTemplate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_TEMPLATE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_TEMPLATE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_TEMPLATE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmsTemplate record);
}