package com.bizwink.persistence;

import com.bizwink.po.PotetialBidder;
import com.bizwink.po.PotetialBidderExample;

public interface PotetialBidderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_potetialbidder
     *
     * @mbggenerated
     */
    int countByExample(PotetialBidderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_potetialbidder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_potetialbidder
     *
     * @mbggenerated
     */
    int insert(PotetialBidder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_potetialbidder
     *
     * @mbggenerated
     */
    int insertSelective(PotetialBidder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_potetialbidder
     *
     * @mbggenerated
     */
    PotetialBidder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_potetialbidder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PotetialBidder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_potetialbidder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PotetialBidder record);
}