package com.bizwink.persistence;

import com.bizwink.po.WinResultsNotice;
import com.bizwink.po.WinResultsNoticeExample;
import com.bizwink.po.WinResultsNoticeKey;
import com.bizwink.po.WinResultsNoticeWithBLOBs;
import com.bizwink.vo.voWinResultsNotice;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;
import java.util.Map;

public interface WinResultsNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    int countByExample(WinResultsNoticeExample example);

    BigDecimal getWinResultsNoticeCount(Timestamp now);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(WinResultsNoticeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    int insert(WinResultsNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    int insertSelective(WinResultsNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    WinResultsNoticeWithBLOBs selectByPrimaryKey(WinResultsNoticeKey key);

    WinResultsNoticeWithBLOBs selectByUUID(String uuid);

    List<voWinResultsNotice> getWinResultsNoticeList(Map params);

    List<voWinResultsNotice> getTopWinResultsNotice(Map params);

    BigDecimal SearchWinResultsNoticeCount(Map params);

    List<voWinResultsNotice> SearchWinResultsNoticeList(Map params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WinResultsNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(WinResultsNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WinResultsNotice record);
}