package com.bizwink.mysql.persistence;

import com.bizwink.mysql.po.Orders;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_orders
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long ORDERID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_orders
     *
     * @mbggenerated
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_orders
     *
     * @mbggenerated
     */
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_orders
     *
     * @mbggenerated
     */
    Orders selectByPrimaryKey(Long ORDERID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_orders
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_orders
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Orders record);
}