package com.bizwink.po;

import java.io.Serializable;
import java.util.Date;

public class Addressinfofororder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_addressinfofororder.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_addressinfofororder.ORDERID
     *
     * @mbggenerated
     */
    private Long ORDERID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_addressinfofororder.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_addressinfofororder.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_addressinfofororder.provinces
     *
     * @mbggenerated
     */
    private String provinces;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_addressinfofororder.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_addressinfofororder.zone
     *
     * @mbggenerated
     */
    private String zone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_addressinfofororder.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_addressinfofororder.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_addressinfofororder.zip
     *
     * @mbggenerated
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_addressinfofororder.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_addressinfofororder.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_addressinfofororder.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_addressinfofororder.notes
     *
     * @mbggenerated
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_addressinfofororder.id
     *
     * @return the value of tbl_addressinfofororder.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_addressinfofororder.id
     *
     * @param id the value for tbl_addressinfofororder.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_addressinfofororder.ORDERID
     *
     * @return the value of tbl_addressinfofororder.ORDERID
     *
     * @mbggenerated
     */
    public Long getORDERID() {
        return ORDERID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_addressinfofororder.ORDERID
     *
     * @param ORDERID the value for tbl_addressinfofororder.ORDERID
     *
     * @mbggenerated
     */
    public void setORDERID(Long ORDERID) {
        this.ORDERID = ORDERID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_addressinfofororder.userid
     *
     * @return the value of tbl_addressinfofororder.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_addressinfofororder.userid
     *
     * @param userid the value for tbl_addressinfofororder.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_addressinfofororder.name
     *
     * @return the value of tbl_addressinfofororder.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_addressinfofororder.name
     *
     * @param name the value for tbl_addressinfofororder.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_addressinfofororder.provinces
     *
     * @return the value of tbl_addressinfofororder.provinces
     *
     * @mbggenerated
     */
    public String getProvinces() {
        return provinces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_addressinfofororder.provinces
     *
     * @param provinces the value for tbl_addressinfofororder.provinces
     *
     * @mbggenerated
     */
    public void setProvinces(String provinces) {
        this.provinces = provinces == null ? null : provinces.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_addressinfofororder.city
     *
     * @return the value of tbl_addressinfofororder.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_addressinfofororder.city
     *
     * @param city the value for tbl_addressinfofororder.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_addressinfofororder.zone
     *
     * @return the value of tbl_addressinfofororder.zone
     *
     * @mbggenerated
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_addressinfofororder.zone
     *
     * @param zone the value for tbl_addressinfofororder.zone
     *
     * @mbggenerated
     */
    public void setZone(String zone) {
        this.zone = zone == null ? null : zone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_addressinfofororder.mobile
     *
     * @return the value of tbl_addressinfofororder.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_addressinfofororder.mobile
     *
     * @param mobile the value for tbl_addressinfofororder.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_addressinfofororder.phone
     *
     * @return the value of tbl_addressinfofororder.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_addressinfofororder.phone
     *
     * @param phone the value for tbl_addressinfofororder.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_addressinfofororder.zip
     *
     * @return the value of tbl_addressinfofororder.zip
     *
     * @mbggenerated
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_addressinfofororder.zip
     *
     * @param zip the value for tbl_addressinfofororder.zip
     *
     * @mbggenerated
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_addressinfofororder.address
     *
     * @return the value of tbl_addressinfofororder.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_addressinfofororder.address
     *
     * @param address the value for tbl_addressinfofororder.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_addressinfofororder.createdate
     *
     * @return the value of tbl_addressinfofororder.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_addressinfofororder.createdate
     *
     * @param createdate the value for tbl_addressinfofororder.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_addressinfofororder.email
     *
     * @return the value of tbl_addressinfofororder.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_addressinfofororder.email
     *
     * @param email the value for tbl_addressinfofororder.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_addressinfofororder.notes
     *
     * @return the value of tbl_addressinfofororder.notes
     *
     * @mbggenerated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_addressinfofororder.notes
     *
     * @param notes the value for tbl_addressinfofororder.notes
     *
     * @mbggenerated
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}