package com.bizwink.po;

import java.math.BigDecimal;
import java.util.Date;

public class ArticleClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ARTICLE_CLASS.ID
     *
     * @mbggenerated
     */
    private BigDecimal ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ARTICLE_CLASS.ARTICLEID
     *
     * @mbggenerated
     */
    private BigDecimal ARTICLEID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ARTICLE_CLASS.PROJCODE
     *
     * @mbggenerated
     */
    private String PROJCODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ARTICLE_CLASS.MAJORCODE
     *
     * @mbggenerated
     */
    private String MAJORCODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ARTICLE_CLASS.CLASSCODE
     *
     * @mbggenerated
     */
    private String CLASSCODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ARTICLE_CLASS.CLASSNAME
     *
     * @mbggenerated
     */
    private String CLASSNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ARTICLE_CLASS.PRICE
     *
     * @mbggenerated
     */
    private BigDecimal PRICE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ARTICLE_CLASS.CLASSHOUR
     *
     * @mbggenerated
     */
    private String CLASSHOUR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ARTICLE_CLASS.CREATEDATE
     *
     * @mbggenerated
     */
    private Date CREATEDATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ARTICLE_CLASS.ID
     *
     * @return the value of TBL_ARTICLE_CLASS.ID
     *
     * @mbggenerated
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ARTICLE_CLASS.ID
     *
     * @param ID the value for TBL_ARTICLE_CLASS.ID
     *
     * @mbggenerated
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ARTICLE_CLASS.ARTICLEID
     *
     * @return the value of TBL_ARTICLE_CLASS.ARTICLEID
     *
     * @mbggenerated
     */
    public BigDecimal getARTICLEID() {
        return ARTICLEID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ARTICLE_CLASS.ARTICLEID
     *
     * @param ARTICLEID the value for TBL_ARTICLE_CLASS.ARTICLEID
     *
     * @mbggenerated
     */
    public void setARTICLEID(BigDecimal ARTICLEID) {
        this.ARTICLEID = ARTICLEID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ARTICLE_CLASS.PROJCODE
     *
     * @return the value of TBL_ARTICLE_CLASS.PROJCODE
     *
     * @mbggenerated
     */
    public String getPROJCODE() {
        return PROJCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ARTICLE_CLASS.PROJCODE
     *
     * @param PROJCODE the value for TBL_ARTICLE_CLASS.PROJCODE
     *
     * @mbggenerated
     */
    public void setPROJCODE(String PROJCODE) {
        this.PROJCODE = PROJCODE == null ? null : PROJCODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ARTICLE_CLASS.MAJORCODE
     *
     * @return the value of TBL_ARTICLE_CLASS.MAJORCODE
     *
     * @mbggenerated
     */
    public String getMAJORCODE() {
        return MAJORCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ARTICLE_CLASS.MAJORCODE
     *
     * @param MAJORCODE the value for TBL_ARTICLE_CLASS.MAJORCODE
     *
     * @mbggenerated
     */
    public void setMAJORCODE(String MAJORCODE) {
        this.MAJORCODE = MAJORCODE == null ? null : MAJORCODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ARTICLE_CLASS.CLASSCODE
     *
     * @return the value of TBL_ARTICLE_CLASS.CLASSCODE
     *
     * @mbggenerated
     */
    public String getCLASSCODE() {
        return CLASSCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ARTICLE_CLASS.CLASSCODE
     *
     * @param CLASSCODE the value for TBL_ARTICLE_CLASS.CLASSCODE
     *
     * @mbggenerated
     */
    public void setCLASSCODE(String CLASSCODE) {
        this.CLASSCODE = CLASSCODE == null ? null : CLASSCODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ARTICLE_CLASS.CLASSNAME
     *
     * @return the value of TBL_ARTICLE_CLASS.CLASSNAME
     *
     * @mbggenerated
     */
    public String getCLASSNAME() {
        return CLASSNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ARTICLE_CLASS.CLASSNAME
     *
     * @param CLASSNAME the value for TBL_ARTICLE_CLASS.CLASSNAME
     *
     * @mbggenerated
     */
    public void setCLASSNAME(String CLASSNAME) {
        this.CLASSNAME = CLASSNAME == null ? null : CLASSNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ARTICLE_CLASS.PRICE
     *
     * @return the value of TBL_ARTICLE_CLASS.PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getPRICE() {
        return PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ARTICLE_CLASS.PRICE
     *
     * @param PRICE the value for TBL_ARTICLE_CLASS.PRICE
     *
     * @mbggenerated
     */
    public void setPRICE(BigDecimal PRICE) {
        this.PRICE = PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ARTICLE_CLASS.CLASSHOUR
     *
     * @return the value of TBL_ARTICLE_CLASS.CLASSHOUR
     *
     * @mbggenerated
     */
    public String getCLASSHOUR() {
        return CLASSHOUR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ARTICLE_CLASS.CLASSHOUR
     *
     * @param CLASSHOUR the value for TBL_ARTICLE_CLASS.CLASSHOUR
     *
     * @mbggenerated
     */
    public void setCLASSHOUR(String CLASSHOUR) {
        this.CLASSHOUR = CLASSHOUR == null ? null : CLASSHOUR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ARTICLE_CLASS.CREATEDATE
     *
     * @return the value of TBL_ARTICLE_CLASS.CREATEDATE
     *
     * @mbggenerated
     */
    public Date getCREATEDATE() {
        return CREATEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ARTICLE_CLASS.CREATEDATE
     *
     * @param CREATEDATE the value for TBL_ARTICLE_CLASS.CREATEDATE
     *
     * @mbggenerated
     */
    public void setCREATEDATE(Date CREATEDATE) {
        this.CREATEDATE = CREATEDATE;
    }
}