package com.bizwink.po;

import java.math.BigDecimal;
import java.util.Date;

public class LeaveWord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.ID
     *
     * @mbggenerated
     */
    private BigDecimal ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.SITEID
     *
     * @mbggenerated
     */
    private BigDecimal SITEID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.USERID
     *
     * @mbggenerated
     */
    private String USERID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.FLAG
     *
     * @mbggenerated
     */
    private BigDecimal FLAG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.TITLE
     *
     * @mbggenerated
     */
    private String TITLE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.CONTENT
     *
     * @mbggenerated
     */
    private String CONTENT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.WRITEDATE
     *
     * @mbggenerated
     */
    private Date WRITEDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.COMPANY
     *
     * @mbggenerated
     */
    private String COMPANY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.LINKMAN
     *
     * @mbggenerated
     */
    private String LINKMAN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.LINKS
     *
     * @mbggenerated
     */
    private String LINKS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.ZIP
     *
     * @mbggenerated
     */
    private String ZIP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.EMAIL
     *
     * @mbggenerated
     */
    private String EMAIL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.PHONE
     *
     * @mbggenerated
     */
    private String PHONE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.FORMID
     *
     * @mbggenerated
     */
    private BigDecimal FORMID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.DEPARTMENTID
     *
     * @mbggenerated
     */
    private BigDecimal DEPARTMENTID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.RETCONTENT
     *
     * @mbggenerated
     */
    private String RETCONTENT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.AUDITOR
     *
     * @mbggenerated
     */
    private String AUDITOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.AUDITFLAG
     *
     * @mbggenerated
     */
    private BigDecimal AUDITFLAG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.PROCESSOR
     *
     * @mbggenerated
     */
    private String PROCESSOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.MPHONE
     *
     * @mbggenerated
     */
    private String MPHONE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.COLUMNID
     *
     * @mbggenerated
     */
    private BigDecimal COLUMNID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.CODE
     *
     * @mbggenerated
     */
    private String CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.SEX
     *
     * @mbggenerated
     */
    private BigDecimal SEX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.VALID
     *
     * @mbggenerated
     */
    private BigDecimal VALID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.VALIDREASON
     *
     * @mbggenerated
     */
    private String VALIDREASON;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.DATEFROMDEPT
     *
     * @mbggenerated
     */
    private Date DATEFROMDEPT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.FINALFLAG
     *
     * @mbggenerated
     */
    private BigDecimal FINALFLAG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LEAVEWORD.ENDTOUSER
     *
     * @mbggenerated
     */
    private Date ENDTOUSER;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.ID
     *
     * @return the value of TBL_LEAVEWORD.ID
     *
     * @mbggenerated
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.ID
     *
     * @param ID the value for TBL_LEAVEWORD.ID
     *
     * @mbggenerated
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.SITEID
     *
     * @return the value of TBL_LEAVEWORD.SITEID
     *
     * @mbggenerated
     */
    public BigDecimal getSITEID() {
        return SITEID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.SITEID
     *
     * @param SITEID the value for TBL_LEAVEWORD.SITEID
     *
     * @mbggenerated
     */
    public void setSITEID(BigDecimal SITEID) {
        this.SITEID = SITEID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.USERID
     *
     * @return the value of TBL_LEAVEWORD.USERID
     *
     * @mbggenerated
     */
    public String getUSERID() {
        return USERID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.USERID
     *
     * @param USERID the value for TBL_LEAVEWORD.USERID
     *
     * @mbggenerated
     */
    public void setUSERID(String USERID) {
        this.USERID = USERID == null ? null : USERID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.FLAG
     *
     * @return the value of TBL_LEAVEWORD.FLAG
     *
     * @mbggenerated
     */
    public BigDecimal getFLAG() {
        return FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.FLAG
     *
     * @param FLAG the value for TBL_LEAVEWORD.FLAG
     *
     * @mbggenerated
     */
    public void setFLAG(BigDecimal FLAG) {
        this.FLAG = FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.TITLE
     *
     * @return the value of TBL_LEAVEWORD.TITLE
     *
     * @mbggenerated
     */
    public String getTITLE() {
        return TITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.TITLE
     *
     * @param TITLE the value for TBL_LEAVEWORD.TITLE
     *
     * @mbggenerated
     */
    public void setTITLE(String TITLE) {
        this.TITLE = TITLE == null ? null : TITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.CONTENT
     *
     * @return the value of TBL_LEAVEWORD.CONTENT
     *
     * @mbggenerated
     */
    public String getCONTENT() {
        return CONTENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.CONTENT
     *
     * @param CONTENT the value for TBL_LEAVEWORD.CONTENT
     *
     * @mbggenerated
     */
    public void setCONTENT(String CONTENT) {
        this.CONTENT = CONTENT == null ? null : CONTENT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.WRITEDATE
     *
     * @return the value of TBL_LEAVEWORD.WRITEDATE
     *
     * @mbggenerated
     */
    public Date getWRITEDATE() {
        return WRITEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.WRITEDATE
     *
     * @param WRITEDATE the value for TBL_LEAVEWORD.WRITEDATE
     *
     * @mbggenerated
     */
    public void setWRITEDATE(Date WRITEDATE) {
        this.WRITEDATE = WRITEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.COMPANY
     *
     * @return the value of TBL_LEAVEWORD.COMPANY
     *
     * @mbggenerated
     */
    public String getCOMPANY() {
        return COMPANY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.COMPANY
     *
     * @param COMPANY the value for TBL_LEAVEWORD.COMPANY
     *
     * @mbggenerated
     */
    public void setCOMPANY(String COMPANY) {
        this.COMPANY = COMPANY == null ? null : COMPANY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.LINKMAN
     *
     * @return the value of TBL_LEAVEWORD.LINKMAN
     *
     * @mbggenerated
     */
    public String getLINKMAN() {
        return LINKMAN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.LINKMAN
     *
     * @param LINKMAN the value for TBL_LEAVEWORD.LINKMAN
     *
     * @mbggenerated
     */
    public void setLINKMAN(String LINKMAN) {
        this.LINKMAN = LINKMAN == null ? null : LINKMAN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.LINKS
     *
     * @return the value of TBL_LEAVEWORD.LINKS
     *
     * @mbggenerated
     */
    public String getLINKS() {
        return LINKS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.LINKS
     *
     * @param LINKS the value for TBL_LEAVEWORD.LINKS
     *
     * @mbggenerated
     */
    public void setLINKS(String LINKS) {
        this.LINKS = LINKS == null ? null : LINKS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.ZIP
     *
     * @return the value of TBL_LEAVEWORD.ZIP
     *
     * @mbggenerated
     */
    public String getZIP() {
        return ZIP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.ZIP
     *
     * @param ZIP the value for TBL_LEAVEWORD.ZIP
     *
     * @mbggenerated
     */
    public void setZIP(String ZIP) {
        this.ZIP = ZIP == null ? null : ZIP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.EMAIL
     *
     * @return the value of TBL_LEAVEWORD.EMAIL
     *
     * @mbggenerated
     */
    public String getEMAIL() {
        return EMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.EMAIL
     *
     * @param EMAIL the value for TBL_LEAVEWORD.EMAIL
     *
     * @mbggenerated
     */
    public void setEMAIL(String EMAIL) {
        this.EMAIL = EMAIL == null ? null : EMAIL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.PHONE
     *
     * @return the value of TBL_LEAVEWORD.PHONE
     *
     * @mbggenerated
     */
    public String getPHONE() {
        return PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.PHONE
     *
     * @param PHONE the value for TBL_LEAVEWORD.PHONE
     *
     * @mbggenerated
     */
    public void setPHONE(String PHONE) {
        this.PHONE = PHONE == null ? null : PHONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.FORMID
     *
     * @return the value of TBL_LEAVEWORD.FORMID
     *
     * @mbggenerated
     */
    public BigDecimal getFORMID() {
        return FORMID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.FORMID
     *
     * @param FORMID the value for TBL_LEAVEWORD.FORMID
     *
     * @mbggenerated
     */
    public void setFORMID(BigDecimal FORMID) {
        this.FORMID = FORMID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.DEPARTMENTID
     *
     * @return the value of TBL_LEAVEWORD.DEPARTMENTID
     *
     * @mbggenerated
     */
    public BigDecimal getDEPARTMENTID() {
        return DEPARTMENTID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.DEPARTMENTID
     *
     * @param DEPARTMENTID the value for TBL_LEAVEWORD.DEPARTMENTID
     *
     * @mbggenerated
     */
    public void setDEPARTMENTID(BigDecimal DEPARTMENTID) {
        this.DEPARTMENTID = DEPARTMENTID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.RETCONTENT
     *
     * @return the value of TBL_LEAVEWORD.RETCONTENT
     *
     * @mbggenerated
     */
    public String getRETCONTENT() {
        return RETCONTENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.RETCONTENT
     *
     * @param RETCONTENT the value for TBL_LEAVEWORD.RETCONTENT
     *
     * @mbggenerated
     */
    public void setRETCONTENT(String RETCONTENT) {
        this.RETCONTENT = RETCONTENT == null ? null : RETCONTENT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.AUDITOR
     *
     * @return the value of TBL_LEAVEWORD.AUDITOR
     *
     * @mbggenerated
     */
    public String getAUDITOR() {
        return AUDITOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.AUDITOR
     *
     * @param AUDITOR the value for TBL_LEAVEWORD.AUDITOR
     *
     * @mbggenerated
     */
    public void setAUDITOR(String AUDITOR) {
        this.AUDITOR = AUDITOR == null ? null : AUDITOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.AUDITFLAG
     *
     * @return the value of TBL_LEAVEWORD.AUDITFLAG
     *
     * @mbggenerated
     */
    public BigDecimal getAUDITFLAG() {
        return AUDITFLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.AUDITFLAG
     *
     * @param AUDITFLAG the value for TBL_LEAVEWORD.AUDITFLAG
     *
     * @mbggenerated
     */
    public void setAUDITFLAG(BigDecimal AUDITFLAG) {
        this.AUDITFLAG = AUDITFLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.PROCESSOR
     *
     * @return the value of TBL_LEAVEWORD.PROCESSOR
     *
     * @mbggenerated
     */
    public String getPROCESSOR() {
        return PROCESSOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.PROCESSOR
     *
     * @param PROCESSOR the value for TBL_LEAVEWORD.PROCESSOR
     *
     * @mbggenerated
     */
    public void setPROCESSOR(String PROCESSOR) {
        this.PROCESSOR = PROCESSOR == null ? null : PROCESSOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.MPHONE
     *
     * @return the value of TBL_LEAVEWORD.MPHONE
     *
     * @mbggenerated
     */
    public String getMPHONE() {
        return MPHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.MPHONE
     *
     * @param MPHONE the value for TBL_LEAVEWORD.MPHONE
     *
     * @mbggenerated
     */
    public void setMPHONE(String MPHONE) {
        this.MPHONE = MPHONE == null ? null : MPHONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.COLUMNID
     *
     * @return the value of TBL_LEAVEWORD.COLUMNID
     *
     * @mbggenerated
     */
    public BigDecimal getCOLUMNID() {
        return COLUMNID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.COLUMNID
     *
     * @param COLUMNID the value for TBL_LEAVEWORD.COLUMNID
     *
     * @mbggenerated
     */
    public void setCOLUMNID(BigDecimal COLUMNID) {
        this.COLUMNID = COLUMNID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.CODE
     *
     * @return the value of TBL_LEAVEWORD.CODE
     *
     * @mbggenerated
     */
    public String getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.CODE
     *
     * @param CODE the value for TBL_LEAVEWORD.CODE
     *
     * @mbggenerated
     */
    public void setCODE(String CODE) {
        this.CODE = CODE == null ? null : CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.SEX
     *
     * @return the value of TBL_LEAVEWORD.SEX
     *
     * @mbggenerated
     */
    public BigDecimal getSEX() {
        return SEX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.SEX
     *
     * @param SEX the value for TBL_LEAVEWORD.SEX
     *
     * @mbggenerated
     */
    public void setSEX(BigDecimal SEX) {
        this.SEX = SEX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.VALID
     *
     * @return the value of TBL_LEAVEWORD.VALID
     *
     * @mbggenerated
     */
    public BigDecimal getVALID() {
        return VALID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.VALID
     *
     * @param VALID the value for TBL_LEAVEWORD.VALID
     *
     * @mbggenerated
     */
    public void setVALID(BigDecimal VALID) {
        this.VALID = VALID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.VALIDREASON
     *
     * @return the value of TBL_LEAVEWORD.VALIDREASON
     *
     * @mbggenerated
     */
    public String getVALIDREASON() {
        return VALIDREASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.VALIDREASON
     *
     * @param VALIDREASON the value for TBL_LEAVEWORD.VALIDREASON
     *
     * @mbggenerated
     */
    public void setVALIDREASON(String VALIDREASON) {
        this.VALIDREASON = VALIDREASON == null ? null : VALIDREASON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.DATEFROMDEPT
     *
     * @return the value of TBL_LEAVEWORD.DATEFROMDEPT
     *
     * @mbggenerated
     */
    public Date getDATEFROMDEPT() {
        return DATEFROMDEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.DATEFROMDEPT
     *
     * @param DATEFROMDEPT the value for TBL_LEAVEWORD.DATEFROMDEPT
     *
     * @mbggenerated
     */
    public void setDATEFROMDEPT(Date DATEFROMDEPT) {
        this.DATEFROMDEPT = DATEFROMDEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.FINALFLAG
     *
     * @return the value of TBL_LEAVEWORD.FINALFLAG
     *
     * @mbggenerated
     */
    public BigDecimal getFINALFLAG() {
        return FINALFLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.FINALFLAG
     *
     * @param FINALFLAG the value for TBL_LEAVEWORD.FINALFLAG
     *
     * @mbggenerated
     */
    public void setFINALFLAG(BigDecimal FINALFLAG) {
        this.FINALFLAG = FINALFLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LEAVEWORD.ENDTOUSER
     *
     * @return the value of TBL_LEAVEWORD.ENDTOUSER
     *
     * @mbggenerated
     */
    public Date getENDTOUSER() {
        return ENDTOUSER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LEAVEWORD.ENDTOUSER
     *
     * @param ENDTOUSER the value for TBL_LEAVEWORD.ENDTOUSER
     *
     * @mbggenerated
     */
    public void setENDTOUSER(Date ENDTOUSER) {
        this.ENDTOUSER = ENDTOUSER;
    }
}