package com.bizwink.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SectionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table section
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table section
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table section
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    public SectionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table section
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andPurchaseprojcodeIsNull() {
            addCriterion("purchaseprojcode is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseprojcodeIsNotNull() {
            addCriterion("purchaseprojcode is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseprojcodeEqualTo(String value) {
            addCriterion("purchaseprojcode =", value, "purchaseprojcode");
            return (Criteria) this;
        }

        public Criteria andPurchaseprojcodeNotEqualTo(String value) {
            addCriterion("purchaseprojcode <>", value, "purchaseprojcode");
            return (Criteria) this;
        }

        public Criteria andPurchaseprojcodeGreaterThan(String value) {
            addCriterion("purchaseprojcode >", value, "purchaseprojcode");
            return (Criteria) this;
        }

        public Criteria andPurchaseprojcodeGreaterThanOrEqualTo(String value) {
            addCriterion("purchaseprojcode >=", value, "purchaseprojcode");
            return (Criteria) this;
        }

        public Criteria andPurchaseprojcodeLessThan(String value) {
            addCriterion("purchaseprojcode <", value, "purchaseprojcode");
            return (Criteria) this;
        }

        public Criteria andPurchaseprojcodeLessThanOrEqualTo(String value) {
            addCriterion("purchaseprojcode <=", value, "purchaseprojcode");
            return (Criteria) this;
        }

        public Criteria andPurchaseprojcodeLike(String value) {
            addCriterion("purchaseprojcode like", value, "purchaseprojcode");
            return (Criteria) this;
        }

        public Criteria andPurchaseprojcodeNotLike(String value) {
            addCriterion("purchaseprojcode not like", value, "purchaseprojcode");
            return (Criteria) this;
        }

        public Criteria andPurchaseprojcodeIn(List<String> values) {
            addCriterion("purchaseprojcode in", values, "purchaseprojcode");
            return (Criteria) this;
        }

        public Criteria andPurchaseprojcodeNotIn(List<String> values) {
            addCriterion("purchaseprojcode not in", values, "purchaseprojcode");
            return (Criteria) this;
        }

        public Criteria andPurchaseprojcodeBetween(String value1, String value2) {
            addCriterion("purchaseprojcode between", value1, value2, "purchaseprojcode");
            return (Criteria) this;
        }

        public Criteria andPurchaseprojcodeNotBetween(String value1, String value2) {
            addCriterion("purchaseprojcode not between", value1, value2, "purchaseprojcode");
            return (Criteria) this;
        }

        public Criteria andPurchasesectioncodeIsNull() {
            addCriterion("purchasesectioncode is null");
            return (Criteria) this;
        }

        public Criteria andPurchasesectioncodeIsNotNull() {
            addCriterion("purchasesectioncode is not null");
            return (Criteria) this;
        }

        public Criteria andPurchasesectioncodeEqualTo(String value) {
            addCriterion("purchasesectioncode =", value, "purchasesectioncode");
            return (Criteria) this;
        }

        public Criteria andPurchasesectioncodeNotEqualTo(String value) {
            addCriterion("purchasesectioncode <>", value, "purchasesectioncode");
            return (Criteria) this;
        }

        public Criteria andPurchasesectioncodeGreaterThan(String value) {
            addCriterion("purchasesectioncode >", value, "purchasesectioncode");
            return (Criteria) this;
        }

        public Criteria andPurchasesectioncodeGreaterThanOrEqualTo(String value) {
            addCriterion("purchasesectioncode >=", value, "purchasesectioncode");
            return (Criteria) this;
        }

        public Criteria andPurchasesectioncodeLessThan(String value) {
            addCriterion("purchasesectioncode <", value, "purchasesectioncode");
            return (Criteria) this;
        }

        public Criteria andPurchasesectioncodeLessThanOrEqualTo(String value) {
            addCriterion("purchasesectioncode <=", value, "purchasesectioncode");
            return (Criteria) this;
        }

        public Criteria andPurchasesectioncodeLike(String value) {
            addCriterion("purchasesectioncode like", value, "purchasesectioncode");
            return (Criteria) this;
        }

        public Criteria andPurchasesectioncodeNotLike(String value) {
            addCriterion("purchasesectioncode not like", value, "purchasesectioncode");
            return (Criteria) this;
        }

        public Criteria andPurchasesectioncodeIn(List<String> values) {
            addCriterion("purchasesectioncode in", values, "purchasesectioncode");
            return (Criteria) this;
        }

        public Criteria andPurchasesectioncodeNotIn(List<String> values) {
            addCriterion("purchasesectioncode not in", values, "purchasesectioncode");
            return (Criteria) this;
        }

        public Criteria andPurchasesectioncodeBetween(String value1, String value2) {
            addCriterion("purchasesectioncode between", value1, value2, "purchasesectioncode");
            return (Criteria) this;
        }

        public Criteria andPurchasesectioncodeNotBetween(String value1, String value2) {
            addCriterion("purchasesectioncode not between", value1, value2, "purchasesectioncode");
            return (Criteria) this;
        }

        public Criteria andUnifieddealcodeIsNull() {
            addCriterion("unifieddealcode is null");
            return (Criteria) this;
        }

        public Criteria andUnifieddealcodeIsNotNull() {
            addCriterion("unifieddealcode is not null");
            return (Criteria) this;
        }

        public Criteria andUnifieddealcodeEqualTo(String value) {
            addCriterion("unifieddealcode =", value, "unifieddealcode");
            return (Criteria) this;
        }

        public Criteria andUnifieddealcodeNotEqualTo(String value) {
            addCriterion("unifieddealcode <>", value, "unifieddealcode");
            return (Criteria) this;
        }

        public Criteria andUnifieddealcodeGreaterThan(String value) {
            addCriterion("unifieddealcode >", value, "unifieddealcode");
            return (Criteria) this;
        }

        public Criteria andUnifieddealcodeGreaterThanOrEqualTo(String value) {
            addCriterion("unifieddealcode >=", value, "unifieddealcode");
            return (Criteria) this;
        }

        public Criteria andUnifieddealcodeLessThan(String value) {
            addCriterion("unifieddealcode <", value, "unifieddealcode");
            return (Criteria) this;
        }

        public Criteria andUnifieddealcodeLessThanOrEqualTo(String value) {
            addCriterion("unifieddealcode <=", value, "unifieddealcode");
            return (Criteria) this;
        }

        public Criteria andUnifieddealcodeLike(String value) {
            addCriterion("unifieddealcode like", value, "unifieddealcode");
            return (Criteria) this;
        }

        public Criteria andUnifieddealcodeNotLike(String value) {
            addCriterion("unifieddealcode not like", value, "unifieddealcode");
            return (Criteria) this;
        }

        public Criteria andUnifieddealcodeIn(List<String> values) {
            addCriterion("unifieddealcode in", values, "unifieddealcode");
            return (Criteria) this;
        }

        public Criteria andUnifieddealcodeNotIn(List<String> values) {
            addCriterion("unifieddealcode not in", values, "unifieddealcode");
            return (Criteria) this;
        }

        public Criteria andUnifieddealcodeBetween(String value1, String value2) {
            addCriterion("unifieddealcode between", value1, value2, "unifieddealcode");
            return (Criteria) this;
        }

        public Criteria andUnifieddealcodeNotBetween(String value1, String value2) {
            addCriterion("unifieddealcode not between", value1, value2, "unifieddealcode");
            return (Criteria) this;
        }

        public Criteria andSectionnameIsNull() {
            addCriterion("sectionname is null");
            return (Criteria) this;
        }

        public Criteria andSectionnameIsNotNull() {
            addCriterion("sectionname is not null");
            return (Criteria) this;
        }

        public Criteria andSectionnameEqualTo(String value) {
            addCriterion("sectionname =", value, "sectionname");
            return (Criteria) this;
        }

        public Criteria andSectionnameNotEqualTo(String value) {
            addCriterion("sectionname <>", value, "sectionname");
            return (Criteria) this;
        }

        public Criteria andSectionnameGreaterThan(String value) {
            addCriterion("sectionname >", value, "sectionname");
            return (Criteria) this;
        }

        public Criteria andSectionnameGreaterThanOrEqualTo(String value) {
            addCriterion("sectionname >=", value, "sectionname");
            return (Criteria) this;
        }

        public Criteria andSectionnameLessThan(String value) {
            addCriterion("sectionname <", value, "sectionname");
            return (Criteria) this;
        }

        public Criteria andSectionnameLessThanOrEqualTo(String value) {
            addCriterion("sectionname <=", value, "sectionname");
            return (Criteria) this;
        }

        public Criteria andSectionnameLike(String value) {
            addCriterion("sectionname like", value, "sectionname");
            return (Criteria) this;
        }

        public Criteria andSectionnameNotLike(String value) {
            addCriterion("sectionname not like", value, "sectionname");
            return (Criteria) this;
        }

        public Criteria andSectionnameIn(List<String> values) {
            addCriterion("sectionname in", values, "sectionname");
            return (Criteria) this;
        }

        public Criteria andSectionnameNotIn(List<String> values) {
            addCriterion("sectionname not in", values, "sectionname");
            return (Criteria) this;
        }

        public Criteria andSectionnameBetween(String value1, String value2) {
            addCriterion("sectionname between", value1, value2, "sectionname");
            return (Criteria) this;
        }

        public Criteria andSectionnameNotBetween(String value1, String value2) {
            addCriterion("sectionname not between", value1, value2, "sectionname");
            return (Criteria) this;
        }

        public Criteria andBugdetIsNull() {
            addCriterion("bugdet is null");
            return (Criteria) this;
        }

        public Criteria andBugdetIsNotNull() {
            addCriterion("bugdet is not null");
            return (Criteria) this;
        }

        public Criteria andBugdetEqualTo(BigDecimal value) {
            addCriterion("bugdet =", value, "bugdet");
            return (Criteria) this;
        }

        public Criteria andBugdetNotEqualTo(BigDecimal value) {
            addCriterion("bugdet <>", value, "bugdet");
            return (Criteria) this;
        }

        public Criteria andBugdetGreaterThan(BigDecimal value) {
            addCriterion("bugdet >", value, "bugdet");
            return (Criteria) this;
        }

        public Criteria andBugdetGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bugdet >=", value, "bugdet");
            return (Criteria) this;
        }

        public Criteria andBugdetLessThan(BigDecimal value) {
            addCriterion("bugdet <", value, "bugdet");
            return (Criteria) this;
        }

        public Criteria andBugdetLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bugdet <=", value, "bugdet");
            return (Criteria) this;
        }

        public Criteria andBugdetIn(List<BigDecimal> values) {
            addCriterion("bugdet in", values, "bugdet");
            return (Criteria) this;
        }

        public Criteria andBugdetNotIn(List<BigDecimal> values) {
            addCriterion("bugdet not in", values, "bugdet");
            return (Criteria) this;
        }

        public Criteria andBugdetBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bugdet between", value1, value2, "bugdet");
            return (Criteria) this;
        }

        public Criteria andBugdetNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bugdet not between", value1, value2, "bugdet");
            return (Criteria) this;
        }

        public Criteria andBcurrencyIsNull() {
            addCriterion("bcurrency is null");
            return (Criteria) this;
        }

        public Criteria andBcurrencyIsNotNull() {
            addCriterion("bcurrency is not null");
            return (Criteria) this;
        }

        public Criteria andBcurrencyEqualTo(String value) {
            addCriterion("bcurrency =", value, "bcurrency");
            return (Criteria) this;
        }

        public Criteria andBcurrencyNotEqualTo(String value) {
            addCriterion("bcurrency <>", value, "bcurrency");
            return (Criteria) this;
        }

        public Criteria andBcurrencyGreaterThan(String value) {
            addCriterion("bcurrency >", value, "bcurrency");
            return (Criteria) this;
        }

        public Criteria andBcurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("bcurrency >=", value, "bcurrency");
            return (Criteria) this;
        }

        public Criteria andBcurrencyLessThan(String value) {
            addCriterion("bcurrency <", value, "bcurrency");
            return (Criteria) this;
        }

        public Criteria andBcurrencyLessThanOrEqualTo(String value) {
            addCriterion("bcurrency <=", value, "bcurrency");
            return (Criteria) this;
        }

        public Criteria andBcurrencyLike(String value) {
            addCriterion("bcurrency like", value, "bcurrency");
            return (Criteria) this;
        }

        public Criteria andBcurrencyNotLike(String value) {
            addCriterion("bcurrency not like", value, "bcurrency");
            return (Criteria) this;
        }

        public Criteria andBcurrencyIn(List<String> values) {
            addCriterion("bcurrency in", values, "bcurrency");
            return (Criteria) this;
        }

        public Criteria andBcurrencyNotIn(List<String> values) {
            addCriterion("bcurrency not in", values, "bcurrency");
            return (Criteria) this;
        }

        public Criteria andBcurrencyBetween(String value1, String value2) {
            addCriterion("bcurrency between", value1, value2, "bcurrency");
            return (Criteria) this;
        }

        public Criteria andBcurrencyNotBetween(String value1, String value2) {
            addCriterion("bcurrency not between", value1, value2, "bcurrency");
            return (Criteria) this;
        }

        public Criteria andBcurrencyunitIsNull() {
            addCriterion("bcurrencyunit is null");
            return (Criteria) this;
        }

        public Criteria andBcurrencyunitIsNotNull() {
            addCriterion("bcurrencyunit is not null");
            return (Criteria) this;
        }

        public Criteria andBcurrencyunitEqualTo(String value) {
            addCriterion("bcurrencyunit =", value, "bcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andBcurrencyunitNotEqualTo(String value) {
            addCriterion("bcurrencyunit <>", value, "bcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andBcurrencyunitGreaterThan(String value) {
            addCriterion("bcurrencyunit >", value, "bcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andBcurrencyunitGreaterThanOrEqualTo(String value) {
            addCriterion("bcurrencyunit >=", value, "bcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andBcurrencyunitLessThan(String value) {
            addCriterion("bcurrencyunit <", value, "bcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andBcurrencyunitLessThanOrEqualTo(String value) {
            addCriterion("bcurrencyunit <=", value, "bcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andBcurrencyunitLike(String value) {
            addCriterion("bcurrencyunit like", value, "bcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andBcurrencyunitNotLike(String value) {
            addCriterion("bcurrencyunit not like", value, "bcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andBcurrencyunitIn(List<String> values) {
            addCriterion("bcurrencyunit in", values, "bcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andBcurrencyunitNotIn(List<String> values) {
            addCriterion("bcurrencyunit not in", values, "bcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andBcurrencyunitBetween(String value1, String value2) {
            addCriterion("bcurrencyunit between", value1, value2, "bcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andBcurrencyunitNotBetween(String value1, String value2) {
            addCriterion("bcurrencyunit not between", value1, value2, "bcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andMarginIsNull() {
            addCriterion("margin is null");
            return (Criteria) this;
        }

        public Criteria andMarginIsNotNull() {
            addCriterion("margin is not null");
            return (Criteria) this;
        }

        public Criteria andMarginEqualTo(BigDecimal value) {
            addCriterion("margin =", value, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginNotEqualTo(BigDecimal value) {
            addCriterion("margin <>", value, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginGreaterThan(BigDecimal value) {
            addCriterion("margin >", value, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("margin >=", value, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginLessThan(BigDecimal value) {
            addCriterion("margin <", value, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginLessThanOrEqualTo(BigDecimal value) {
            addCriterion("margin <=", value, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginIn(List<BigDecimal> values) {
            addCriterion("margin in", values, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginNotIn(List<BigDecimal> values) {
            addCriterion("margin not in", values, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("margin between", value1, value2, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("margin not between", value1, value2, "margin");
            return (Criteria) this;
        }

        public Criteria andMcurrencyIsNull() {
            addCriterion("mcurrency is null");
            return (Criteria) this;
        }

        public Criteria andMcurrencyIsNotNull() {
            addCriterion("mcurrency is not null");
            return (Criteria) this;
        }

        public Criteria andMcurrencyEqualTo(String value) {
            addCriterion("mcurrency =", value, "mcurrency");
            return (Criteria) this;
        }

        public Criteria andMcurrencyNotEqualTo(String value) {
            addCriterion("mcurrency <>", value, "mcurrency");
            return (Criteria) this;
        }

        public Criteria andMcurrencyGreaterThan(String value) {
            addCriterion("mcurrency >", value, "mcurrency");
            return (Criteria) this;
        }

        public Criteria andMcurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("mcurrency >=", value, "mcurrency");
            return (Criteria) this;
        }

        public Criteria andMcurrencyLessThan(String value) {
            addCriterion("mcurrency <", value, "mcurrency");
            return (Criteria) this;
        }

        public Criteria andMcurrencyLessThanOrEqualTo(String value) {
            addCriterion("mcurrency <=", value, "mcurrency");
            return (Criteria) this;
        }

        public Criteria andMcurrencyLike(String value) {
            addCriterion("mcurrency like", value, "mcurrency");
            return (Criteria) this;
        }

        public Criteria andMcurrencyNotLike(String value) {
            addCriterion("mcurrency not like", value, "mcurrency");
            return (Criteria) this;
        }

        public Criteria andMcurrencyIn(List<String> values) {
            addCriterion("mcurrency in", values, "mcurrency");
            return (Criteria) this;
        }

        public Criteria andMcurrencyNotIn(List<String> values) {
            addCriterion("mcurrency not in", values, "mcurrency");
            return (Criteria) this;
        }

        public Criteria andMcurrencyBetween(String value1, String value2) {
            addCriterion("mcurrency between", value1, value2, "mcurrency");
            return (Criteria) this;
        }

        public Criteria andMcurrencyNotBetween(String value1, String value2) {
            addCriterion("mcurrency not between", value1, value2, "mcurrency");
            return (Criteria) this;
        }

        public Criteria andMcurrencyunitIsNull() {
            addCriterion("mcurrencyunit is null");
            return (Criteria) this;
        }

        public Criteria andMcurrencyunitIsNotNull() {
            addCriterion("mcurrencyunit is not null");
            return (Criteria) this;
        }

        public Criteria andMcurrencyunitEqualTo(String value) {
            addCriterion("mcurrencyunit =", value, "mcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andMcurrencyunitNotEqualTo(String value) {
            addCriterion("mcurrencyunit <>", value, "mcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andMcurrencyunitGreaterThan(String value) {
            addCriterion("mcurrencyunit >", value, "mcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andMcurrencyunitGreaterThanOrEqualTo(String value) {
            addCriterion("mcurrencyunit >=", value, "mcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andMcurrencyunitLessThan(String value) {
            addCriterion("mcurrencyunit <", value, "mcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andMcurrencyunitLessThanOrEqualTo(String value) {
            addCriterion("mcurrencyunit <=", value, "mcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andMcurrencyunitLike(String value) {
            addCriterion("mcurrencyunit like", value, "mcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andMcurrencyunitNotLike(String value) {
            addCriterion("mcurrencyunit not like", value, "mcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andMcurrencyunitIn(List<String> values) {
            addCriterion("mcurrencyunit in", values, "mcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andMcurrencyunitNotIn(List<String> values) {
            addCriterion("mcurrencyunit not in", values, "mcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andMcurrencyunitBetween(String value1, String value2) {
            addCriterion("mcurrencyunit between", value1, value2, "mcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andMcurrencyunitNotBetween(String value1, String value2) {
            addCriterion("mcurrencyunit not between", value1, value2, "mcurrencyunit");
            return (Criteria) this;
        }

        public Criteria andSynflagIsNull() {
            addCriterion("synflag is null");
            return (Criteria) this;
        }

        public Criteria andSynflagIsNotNull() {
            addCriterion("synflag is not null");
            return (Criteria) this;
        }

        public Criteria andSynflagEqualTo(String value) {
            addCriterion("synflag =", value, "synflag");
            return (Criteria) this;
        }

        public Criteria andSynflagNotEqualTo(String value) {
            addCriterion("synflag <>", value, "synflag");
            return (Criteria) this;
        }

        public Criteria andSynflagGreaterThan(String value) {
            addCriterion("synflag >", value, "synflag");
            return (Criteria) this;
        }

        public Criteria andSynflagGreaterThanOrEqualTo(String value) {
            addCriterion("synflag >=", value, "synflag");
            return (Criteria) this;
        }

        public Criteria andSynflagLessThan(String value) {
            addCriterion("synflag <", value, "synflag");
            return (Criteria) this;
        }

        public Criteria andSynflagLessThanOrEqualTo(String value) {
            addCriterion("synflag <=", value, "synflag");
            return (Criteria) this;
        }

        public Criteria andSynflagLike(String value) {
            addCriterion("synflag like", value, "synflag");
            return (Criteria) this;
        }

        public Criteria andSynflagNotLike(String value) {
            addCriterion("synflag not like", value, "synflag");
            return (Criteria) this;
        }

        public Criteria andSynflagIn(List<String> values) {
            addCriterion("synflag in", values, "synflag");
            return (Criteria) this;
        }

        public Criteria andSynflagNotIn(List<String> values) {
            addCriterion("synflag not in", values, "synflag");
            return (Criteria) this;
        }

        public Criteria andSynflagBetween(String value1, String value2) {
            addCriterion("synflag between", value1, value2, "synflag");
            return (Criteria) this;
        }

        public Criteria andSynflagNotBetween(String value1, String value2) {
            addCriterion("synflag not between", value1, value2, "synflag");
            return (Criteria) this;
        }

        public Criteria andPurchasemodeIsNull() {
            addCriterion("purchasemode is null");
            return (Criteria) this;
        }

        public Criteria andPurchasemodeIsNotNull() {
            addCriterion("purchasemode is not null");
            return (Criteria) this;
        }

        public Criteria andPurchasemodeEqualTo(String value) {
            addCriterion("purchasemode =", value, "purchasemode");
            return (Criteria) this;
        }

        public Criteria andPurchasemodeNotEqualTo(String value) {
            addCriterion("purchasemode <>", value, "purchasemode");
            return (Criteria) this;
        }

        public Criteria andPurchasemodeGreaterThan(String value) {
            addCriterion("purchasemode >", value, "purchasemode");
            return (Criteria) this;
        }

        public Criteria andPurchasemodeGreaterThanOrEqualTo(String value) {
            addCriterion("purchasemode >=", value, "purchasemode");
            return (Criteria) this;
        }

        public Criteria andPurchasemodeLessThan(String value) {
            addCriterion("purchasemode <", value, "purchasemode");
            return (Criteria) this;
        }

        public Criteria andPurchasemodeLessThanOrEqualTo(String value) {
            addCriterion("purchasemode <=", value, "purchasemode");
            return (Criteria) this;
        }

        public Criteria andPurchasemodeLike(String value) {
            addCriterion("purchasemode like", value, "purchasemode");
            return (Criteria) this;
        }

        public Criteria andPurchasemodeNotLike(String value) {
            addCriterion("purchasemode not like", value, "purchasemode");
            return (Criteria) this;
        }

        public Criteria andPurchasemodeIn(List<String> values) {
            addCriterion("purchasemode in", values, "purchasemode");
            return (Criteria) this;
        }

        public Criteria andPurchasemodeNotIn(List<String> values) {
            addCriterion("purchasemode not in", values, "purchasemode");
            return (Criteria) this;
        }

        public Criteria andPurchasemodeBetween(String value1, String value2) {
            addCriterion("purchasemode between", value1, value2, "purchasemode");
            return (Criteria) this;
        }

        public Criteria andPurchasemodeNotBetween(String value1, String value2) {
            addCriterion("purchasemode not between", value1, value2, "purchasemode");
            return (Criteria) this;
        }

        public Criteria andPlatformcodeIsNull() {
            addCriterion("platformcode is null");
            return (Criteria) this;
        }

        public Criteria andPlatformcodeIsNotNull() {
            addCriterion("platformcode is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformcodeEqualTo(String value) {
            addCriterion("platformcode =", value, "platformcode");
            return (Criteria) this;
        }

        public Criteria andPlatformcodeNotEqualTo(String value) {
            addCriterion("platformcode <>", value, "platformcode");
            return (Criteria) this;
        }

        public Criteria andPlatformcodeGreaterThan(String value) {
            addCriterion("platformcode >", value, "platformcode");
            return (Criteria) this;
        }

        public Criteria andPlatformcodeGreaterThanOrEqualTo(String value) {
            addCriterion("platformcode >=", value, "platformcode");
            return (Criteria) this;
        }

        public Criteria andPlatformcodeLessThan(String value) {
            addCriterion("platformcode <", value, "platformcode");
            return (Criteria) this;
        }

        public Criteria andPlatformcodeLessThanOrEqualTo(String value) {
            addCriterion("platformcode <=", value, "platformcode");
            return (Criteria) this;
        }

        public Criteria andPlatformcodeLike(String value) {
            addCriterion("platformcode like", value, "platformcode");
            return (Criteria) this;
        }

        public Criteria andPlatformcodeNotLike(String value) {
            addCriterion("platformcode not like", value, "platformcode");
            return (Criteria) this;
        }

        public Criteria andPlatformcodeIn(List<String> values) {
            addCriterion("platformcode in", values, "platformcode");
            return (Criteria) this;
        }

        public Criteria andPlatformcodeNotIn(List<String> values) {
            addCriterion("platformcode not in", values, "platformcode");
            return (Criteria) this;
        }

        public Criteria andPlatformcodeBetween(String value1, String value2) {
            addCriterion("platformcode between", value1, value2, "platformcode");
            return (Criteria) this;
        }

        public Criteria andPlatformcodeNotBetween(String value1, String value2) {
            addCriterion("platformcode not between", value1, value2, "platformcode");
            return (Criteria) this;
        }

        public Criteria andPlacecodeIsNull() {
            addCriterion("placecode is null");
            return (Criteria) this;
        }

        public Criteria andPlacecodeIsNotNull() {
            addCriterion("placecode is not null");
            return (Criteria) this;
        }

        public Criteria andPlacecodeEqualTo(String value) {
            addCriterion("placecode =", value, "placecode");
            return (Criteria) this;
        }

        public Criteria andPlacecodeNotEqualTo(String value) {
            addCriterion("placecode <>", value, "placecode");
            return (Criteria) this;
        }

        public Criteria andPlacecodeGreaterThan(String value) {
            addCriterion("placecode >", value, "placecode");
            return (Criteria) this;
        }

        public Criteria andPlacecodeGreaterThanOrEqualTo(String value) {
            addCriterion("placecode >=", value, "placecode");
            return (Criteria) this;
        }

        public Criteria andPlacecodeLessThan(String value) {
            addCriterion("placecode <", value, "placecode");
            return (Criteria) this;
        }

        public Criteria andPlacecodeLessThanOrEqualTo(String value) {
            addCriterion("placecode <=", value, "placecode");
            return (Criteria) this;
        }

        public Criteria andPlacecodeLike(String value) {
            addCriterion("placecode like", value, "placecode");
            return (Criteria) this;
        }

        public Criteria andPlacecodeNotLike(String value) {
            addCriterion("placecode not like", value, "placecode");
            return (Criteria) this;
        }

        public Criteria andPlacecodeIn(List<String> values) {
            addCriterion("placecode in", values, "placecode");
            return (Criteria) this;
        }

        public Criteria andPlacecodeNotIn(List<String> values) {
            addCriterion("placecode not in", values, "placecode");
            return (Criteria) this;
        }

        public Criteria andPlacecodeBetween(String value1, String value2) {
            addCriterion("placecode between", value1, value2, "placecode");
            return (Criteria) this;
        }

        public Criteria andPlacecodeNotBetween(String value1, String value2) {
            addCriterion("placecode not between", value1, value2, "placecode");
            return (Criteria) this;
        }

        public Criteria andPubserviceplatcodeIsNull() {
            addCriterion("pubserviceplatcode is null");
            return (Criteria) this;
        }

        public Criteria andPubserviceplatcodeIsNotNull() {
            addCriterion("pubserviceplatcode is not null");
            return (Criteria) this;
        }

        public Criteria andPubserviceplatcodeEqualTo(String value) {
            addCriterion("pubserviceplatcode =", value, "pubserviceplatcode");
            return (Criteria) this;
        }

        public Criteria andPubserviceplatcodeNotEqualTo(String value) {
            addCriterion("pubserviceplatcode <>", value, "pubserviceplatcode");
            return (Criteria) this;
        }

        public Criteria andPubserviceplatcodeGreaterThan(String value) {
            addCriterion("pubserviceplatcode >", value, "pubserviceplatcode");
            return (Criteria) this;
        }

        public Criteria andPubserviceplatcodeGreaterThanOrEqualTo(String value) {
            addCriterion("pubserviceplatcode >=", value, "pubserviceplatcode");
            return (Criteria) this;
        }

        public Criteria andPubserviceplatcodeLessThan(String value) {
            addCriterion("pubserviceplatcode <", value, "pubserviceplatcode");
            return (Criteria) this;
        }

        public Criteria andPubserviceplatcodeLessThanOrEqualTo(String value) {
            addCriterion("pubserviceplatcode <=", value, "pubserviceplatcode");
            return (Criteria) this;
        }

        public Criteria andPubserviceplatcodeLike(String value) {
            addCriterion("pubserviceplatcode like", value, "pubserviceplatcode");
            return (Criteria) this;
        }

        public Criteria andPubserviceplatcodeNotLike(String value) {
            addCriterion("pubserviceplatcode not like", value, "pubserviceplatcode");
            return (Criteria) this;
        }

        public Criteria andPubserviceplatcodeIn(List<String> values) {
            addCriterion("pubserviceplatcode in", values, "pubserviceplatcode");
            return (Criteria) this;
        }

        public Criteria andPubserviceplatcodeNotIn(List<String> values) {
            addCriterion("pubserviceplatcode not in", values, "pubserviceplatcode");
            return (Criteria) this;
        }

        public Criteria andPubserviceplatcodeBetween(String value1, String value2) {
            addCriterion("pubserviceplatcode between", value1, value2, "pubserviceplatcode");
            return (Criteria) this;
        }

        public Criteria andPubserviceplatcodeNotBetween(String value1, String value2) {
            addCriterion("pubserviceplatcode not between", value1, value2, "pubserviceplatcode");
            return (Criteria) this;
        }

        public Criteria andSectionAttachementIsNull() {
            addCriterion("sectionAttachement is null");
            return (Criteria) this;
        }

        public Criteria andSectionAttachementIsNotNull() {
            addCriterion("sectionAttachement is not null");
            return (Criteria) this;
        }

        public Criteria andSectionAttachementEqualTo(String value) {
            addCriterion("sectionAttachement =", value, "sectionAttachement");
            return (Criteria) this;
        }

        public Criteria andSectionAttachementNotEqualTo(String value) {
            addCriterion("sectionAttachement <>", value, "sectionAttachement");
            return (Criteria) this;
        }

        public Criteria andSectionAttachementGreaterThan(String value) {
            addCriterion("sectionAttachement >", value, "sectionAttachement");
            return (Criteria) this;
        }

        public Criteria andSectionAttachementGreaterThanOrEqualTo(String value) {
            addCriterion("sectionAttachement >=", value, "sectionAttachement");
            return (Criteria) this;
        }

        public Criteria andSectionAttachementLessThan(String value) {
            addCriterion("sectionAttachement <", value, "sectionAttachement");
            return (Criteria) this;
        }

        public Criteria andSectionAttachementLessThanOrEqualTo(String value) {
            addCriterion("sectionAttachement <=", value, "sectionAttachement");
            return (Criteria) this;
        }

        public Criteria andSectionAttachementLike(String value) {
            addCriterion("sectionAttachement like", value, "sectionAttachement");
            return (Criteria) this;
        }

        public Criteria andSectionAttachementNotLike(String value) {
            addCriterion("sectionAttachement not like", value, "sectionAttachement");
            return (Criteria) this;
        }

        public Criteria andSectionAttachementIn(List<String> values) {
            addCriterion("sectionAttachement in", values, "sectionAttachement");
            return (Criteria) this;
        }

        public Criteria andSectionAttachementNotIn(List<String> values) {
            addCriterion("sectionAttachement not in", values, "sectionAttachement");
            return (Criteria) this;
        }

        public Criteria andSectionAttachementBetween(String value1, String value2) {
            addCriterion("sectionAttachement between", value1, value2, "sectionAttachement");
            return (Criteria) this;
        }

        public Criteria andSectionAttachementNotBetween(String value1, String value2) {
            addCriterion("sectionAttachement not between", value1, value2, "sectionAttachement");
            return (Criteria) this;
        }

        public Criteria andPrequalformIsNull() {
            addCriterion("prequalform is null");
            return (Criteria) this;
        }

        public Criteria andPrequalformIsNotNull() {
            addCriterion("prequalform is not null");
            return (Criteria) this;
        }

        public Criteria andPrequalformEqualTo(String value) {
            addCriterion("prequalform =", value, "prequalform");
            return (Criteria) this;
        }

        public Criteria andPrequalformNotEqualTo(String value) {
            addCriterion("prequalform <>", value, "prequalform");
            return (Criteria) this;
        }

        public Criteria andPrequalformGreaterThan(String value) {
            addCriterion("prequalform >", value, "prequalform");
            return (Criteria) this;
        }

        public Criteria andPrequalformGreaterThanOrEqualTo(String value) {
            addCriterion("prequalform >=", value, "prequalform");
            return (Criteria) this;
        }

        public Criteria andPrequalformLessThan(String value) {
            addCriterion("prequalform <", value, "prequalform");
            return (Criteria) this;
        }

        public Criteria andPrequalformLessThanOrEqualTo(String value) {
            addCriterion("prequalform <=", value, "prequalform");
            return (Criteria) this;
        }

        public Criteria andPrequalformLike(String value) {
            addCriterion("prequalform like", value, "prequalform");
            return (Criteria) this;
        }

        public Criteria andPrequalformNotLike(String value) {
            addCriterion("prequalform not like", value, "prequalform");
            return (Criteria) this;
        }

        public Criteria andPrequalformIn(List<String> values) {
            addCriterion("prequalform in", values, "prequalform");
            return (Criteria) this;
        }

        public Criteria andPrequalformNotIn(List<String> values) {
            addCriterion("prequalform not in", values, "prequalform");
            return (Criteria) this;
        }

        public Criteria andPrequalformBetween(String value1, String value2) {
            addCriterion("prequalform between", value1, value2, "prequalform");
            return (Criteria) this;
        }

        public Criteria andPrequalformNotBetween(String value1, String value2) {
            addCriterion("prequalform not between", value1, value2, "prequalform");
            return (Criteria) this;
        }

        public Criteria andIssetupuppriceIsNull() {
            addCriterion("issetupupprice is null");
            return (Criteria) this;
        }

        public Criteria andIssetupuppriceIsNotNull() {
            addCriterion("issetupupprice is not null");
            return (Criteria) this;
        }

        public Criteria andIssetupuppriceEqualTo(Integer value) {
            addCriterion("issetupupprice =", value, "issetupupprice");
            return (Criteria) this;
        }

        public Criteria andIssetupuppriceNotEqualTo(Integer value) {
            addCriterion("issetupupprice <>", value, "issetupupprice");
            return (Criteria) this;
        }

        public Criteria andIssetupuppriceGreaterThan(Integer value) {
            addCriterion("issetupupprice >", value, "issetupupprice");
            return (Criteria) this;
        }

        public Criteria andIssetupuppriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("issetupupprice >=", value, "issetupupprice");
            return (Criteria) this;
        }

        public Criteria andIssetupuppriceLessThan(Integer value) {
            addCriterion("issetupupprice <", value, "issetupupprice");
            return (Criteria) this;
        }

        public Criteria andIssetupuppriceLessThanOrEqualTo(Integer value) {
            addCriterion("issetupupprice <=", value, "issetupupprice");
            return (Criteria) this;
        }

        public Criteria andIssetupuppriceIn(List<Integer> values) {
            addCriterion("issetupupprice in", values, "issetupupprice");
            return (Criteria) this;
        }

        public Criteria andIssetupuppriceNotIn(List<Integer> values) {
            addCriterion("issetupupprice not in", values, "issetupupprice");
            return (Criteria) this;
        }

        public Criteria andIssetupuppriceBetween(Integer value1, Integer value2) {
            addCriterion("issetupupprice between", value1, value2, "issetupupprice");
            return (Criteria) this;
        }

        public Criteria andIssetupuppriceNotBetween(Integer value1, Integer value2) {
            addCriterion("issetupupprice not between", value1, value2, "issetupupprice");
            return (Criteria) this;
        }

        public Criteria andUppriceIsNull() {
            addCriterion("upprice is null");
            return (Criteria) this;
        }

        public Criteria andUppriceIsNotNull() {
            addCriterion("upprice is not null");
            return (Criteria) this;
        }

        public Criteria andUppriceEqualTo(BigDecimal value) {
            addCriterion("upprice =", value, "upprice");
            return (Criteria) this;
        }

        public Criteria andUppriceNotEqualTo(BigDecimal value) {
            addCriterion("upprice <>", value, "upprice");
            return (Criteria) this;
        }

        public Criteria andUppriceGreaterThan(BigDecimal value) {
            addCriterion("upprice >", value, "upprice");
            return (Criteria) this;
        }

        public Criteria andUppriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("upprice >=", value, "upprice");
            return (Criteria) this;
        }

        public Criteria andUppriceLessThan(BigDecimal value) {
            addCriterion("upprice <", value, "upprice");
            return (Criteria) this;
        }

        public Criteria andUppriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("upprice <=", value, "upprice");
            return (Criteria) this;
        }

        public Criteria andUppriceIn(List<BigDecimal> values) {
            addCriterion("upprice in", values, "upprice");
            return (Criteria) this;
        }

        public Criteria andUppriceNotIn(List<BigDecimal> values) {
            addCriterion("upprice not in", values, "upprice");
            return (Criteria) this;
        }

        public Criteria andUppriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("upprice between", value1, value2, "upprice");
            return (Criteria) this;
        }

        public Criteria andUppriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("upprice not between", value1, value2, "upprice");
            return (Criteria) this;
        }

        public Criteria andDetermineroleIsNull() {
            addCriterion("determinerole is null");
            return (Criteria) this;
        }

        public Criteria andDetermineroleIsNotNull() {
            addCriterion("determinerole is not null");
            return (Criteria) this;
        }

        public Criteria andDetermineroleEqualTo(String value) {
            addCriterion("determinerole =", value, "determinerole");
            return (Criteria) this;
        }

        public Criteria andDetermineroleNotEqualTo(String value) {
            addCriterion("determinerole <>", value, "determinerole");
            return (Criteria) this;
        }

        public Criteria andDetermineroleGreaterThan(String value) {
            addCriterion("determinerole >", value, "determinerole");
            return (Criteria) this;
        }

        public Criteria andDetermineroleGreaterThanOrEqualTo(String value) {
            addCriterion("determinerole >=", value, "determinerole");
            return (Criteria) this;
        }

        public Criteria andDetermineroleLessThan(String value) {
            addCriterion("determinerole <", value, "determinerole");
            return (Criteria) this;
        }

        public Criteria andDetermineroleLessThanOrEqualTo(String value) {
            addCriterion("determinerole <=", value, "determinerole");
            return (Criteria) this;
        }

        public Criteria andDetermineroleLike(String value) {
            addCriterion("determinerole like", value, "determinerole");
            return (Criteria) this;
        }

        public Criteria andDetermineroleNotLike(String value) {
            addCriterion("determinerole not like", value, "determinerole");
            return (Criteria) this;
        }

        public Criteria andDetermineroleIn(List<String> values) {
            addCriterion("determinerole in", values, "determinerole");
            return (Criteria) this;
        }

        public Criteria andDetermineroleNotIn(List<String> values) {
            addCriterion("determinerole not in", values, "determinerole");
            return (Criteria) this;
        }

        public Criteria andDetermineroleBetween(String value1, String value2) {
            addCriterion("determinerole between", value1, value2, "determinerole");
            return (Criteria) this;
        }

        public Criteria andDetermineroleNotBetween(String value1, String value2) {
            addCriterion("determinerole not between", value1, value2, "determinerole");
            return (Criteria) this;
        }

        public Criteria andBuspointmethodIsNull() {
            addCriterion("buspointmethod is null");
            return (Criteria) this;
        }

        public Criteria andBuspointmethodIsNotNull() {
            addCriterion("buspointmethod is not null");
            return (Criteria) this;
        }

        public Criteria andBuspointmethodEqualTo(String value) {
            addCriterion("buspointmethod =", value, "buspointmethod");
            return (Criteria) this;
        }

        public Criteria andBuspointmethodNotEqualTo(String value) {
            addCriterion("buspointmethod <>", value, "buspointmethod");
            return (Criteria) this;
        }

        public Criteria andBuspointmethodGreaterThan(String value) {
            addCriterion("buspointmethod >", value, "buspointmethod");
            return (Criteria) this;
        }

        public Criteria andBuspointmethodGreaterThanOrEqualTo(String value) {
            addCriterion("buspointmethod >=", value, "buspointmethod");
            return (Criteria) this;
        }

        public Criteria andBuspointmethodLessThan(String value) {
            addCriterion("buspointmethod <", value, "buspointmethod");
            return (Criteria) this;
        }

        public Criteria andBuspointmethodLessThanOrEqualTo(String value) {
            addCriterion("buspointmethod <=", value, "buspointmethod");
            return (Criteria) this;
        }

        public Criteria andBuspointmethodLike(String value) {
            addCriterion("buspointmethod like", value, "buspointmethod");
            return (Criteria) this;
        }

        public Criteria andBuspointmethodNotLike(String value) {
            addCriterion("buspointmethod not like", value, "buspointmethod");
            return (Criteria) this;
        }

        public Criteria andBuspointmethodIn(List<String> values) {
            addCriterion("buspointmethod in", values, "buspointmethod");
            return (Criteria) this;
        }

        public Criteria andBuspointmethodNotIn(List<String> values) {
            addCriterion("buspointmethod not in", values, "buspointmethod");
            return (Criteria) this;
        }

        public Criteria andBuspointmethodBetween(String value1, String value2) {
            addCriterion("buspointmethod between", value1, value2, "buspointmethod");
            return (Criteria) this;
        }

        public Criteria andBuspointmethodNotBetween(String value1, String value2) {
            addCriterion("buspointmethod not between", value1, value2, "buspointmethod");
            return (Criteria) this;
        }

        public Criteria andBasicpriceIsNull() {
            addCriterion("basicprice is null");
            return (Criteria) this;
        }

        public Criteria andBasicpriceIsNotNull() {
            addCriterion("basicprice is not null");
            return (Criteria) this;
        }

        public Criteria andBasicpriceEqualTo(BigDecimal value) {
            addCriterion("basicprice =", value, "basicprice");
            return (Criteria) this;
        }

        public Criteria andBasicpriceNotEqualTo(BigDecimal value) {
            addCriterion("basicprice <>", value, "basicprice");
            return (Criteria) this;
        }

        public Criteria andBasicpriceGreaterThan(BigDecimal value) {
            addCriterion("basicprice >", value, "basicprice");
            return (Criteria) this;
        }

        public Criteria andBasicpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("basicprice >=", value, "basicprice");
            return (Criteria) this;
        }

        public Criteria andBasicpriceLessThan(BigDecimal value) {
            addCriterion("basicprice <", value, "basicprice");
            return (Criteria) this;
        }

        public Criteria andBasicpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("basicprice <=", value, "basicprice");
            return (Criteria) this;
        }

        public Criteria andBasicpriceIn(List<BigDecimal> values) {
            addCriterion("basicprice in", values, "basicprice");
            return (Criteria) this;
        }

        public Criteria andBasicpriceNotIn(List<BigDecimal> values) {
            addCriterion("basicprice not in", values, "basicprice");
            return (Criteria) this;
        }

        public Criteria andBasicpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("basicprice between", value1, value2, "basicprice");
            return (Criteria) this;
        }

        public Criteria andBasicpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("basicprice not between", value1, value2, "basicprice");
            return (Criteria) this;
        }

        public Criteria andLowdeducationIsNull() {
            addCriterion("lowdeducation is null");
            return (Criteria) this;
        }

        public Criteria andLowdeducationIsNotNull() {
            addCriterion("lowdeducation is not null");
            return (Criteria) this;
        }

        public Criteria andLowdeducationEqualTo(BigDecimal value) {
            addCriterion("lowdeducation =", value, "lowdeducation");
            return (Criteria) this;
        }

        public Criteria andLowdeducationNotEqualTo(BigDecimal value) {
            addCriterion("lowdeducation <>", value, "lowdeducation");
            return (Criteria) this;
        }

        public Criteria andLowdeducationGreaterThan(BigDecimal value) {
            addCriterion("lowdeducation >", value, "lowdeducation");
            return (Criteria) this;
        }

        public Criteria andLowdeducationGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("lowdeducation >=", value, "lowdeducation");
            return (Criteria) this;
        }

        public Criteria andLowdeducationLessThan(BigDecimal value) {
            addCriterion("lowdeducation <", value, "lowdeducation");
            return (Criteria) this;
        }

        public Criteria andLowdeducationLessThanOrEqualTo(BigDecimal value) {
            addCriterion("lowdeducation <=", value, "lowdeducation");
            return (Criteria) this;
        }

        public Criteria andLowdeducationIn(List<BigDecimal> values) {
            addCriterion("lowdeducation in", values, "lowdeducation");
            return (Criteria) this;
        }

        public Criteria andLowdeducationNotIn(List<BigDecimal> values) {
            addCriterion("lowdeducation not in", values, "lowdeducation");
            return (Criteria) this;
        }

        public Criteria andLowdeducationBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lowdeducation between", value1, value2, "lowdeducation");
            return (Criteria) this;
        }

        public Criteria andLowdeducationNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lowdeducation not between", value1, value2, "lowdeducation");
            return (Criteria) this;
        }

        public Criteria andUpdeducationIsNull() {
            addCriterion("updeducation is null");
            return (Criteria) this;
        }

        public Criteria andUpdeducationIsNotNull() {
            addCriterion("updeducation is not null");
            return (Criteria) this;
        }

        public Criteria andUpdeducationEqualTo(BigDecimal value) {
            addCriterion("updeducation =", value, "updeducation");
            return (Criteria) this;
        }

        public Criteria andUpdeducationNotEqualTo(BigDecimal value) {
            addCriterion("updeducation <>", value, "updeducation");
            return (Criteria) this;
        }

        public Criteria andUpdeducationGreaterThan(BigDecimal value) {
            addCriterion("updeducation >", value, "updeducation");
            return (Criteria) this;
        }

        public Criteria andUpdeducationGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("updeducation >=", value, "updeducation");
            return (Criteria) this;
        }

        public Criteria andUpdeducationLessThan(BigDecimal value) {
            addCriterion("updeducation <", value, "updeducation");
            return (Criteria) this;
        }

        public Criteria andUpdeducationLessThanOrEqualTo(BigDecimal value) {
            addCriterion("updeducation <=", value, "updeducation");
            return (Criteria) this;
        }

        public Criteria andUpdeducationIn(List<BigDecimal> values) {
            addCriterion("updeducation in", values, "updeducation");
            return (Criteria) this;
        }

        public Criteria andUpdeducationNotIn(List<BigDecimal> values) {
            addCriterion("updeducation not in", values, "updeducation");
            return (Criteria) this;
        }

        public Criteria andUpdeducationBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("updeducation between", value1, value2, "updeducation");
            return (Criteria) this;
        }

        public Criteria andUpdeducationNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("updeducation not between", value1, value2, "updeducation");
            return (Criteria) this;
        }

        public Criteria andBasicpricenotesIsNull() {
            addCriterion("basicpricenotes is null");
            return (Criteria) this;
        }

        public Criteria andBasicpricenotesIsNotNull() {
            addCriterion("basicpricenotes is not null");
            return (Criteria) this;
        }

        public Criteria andBasicpricenotesEqualTo(String value) {
            addCriterion("basicpricenotes =", value, "basicpricenotes");
            return (Criteria) this;
        }

        public Criteria andBasicpricenotesNotEqualTo(String value) {
            addCriterion("basicpricenotes <>", value, "basicpricenotes");
            return (Criteria) this;
        }

        public Criteria andBasicpricenotesGreaterThan(String value) {
            addCriterion("basicpricenotes >", value, "basicpricenotes");
            return (Criteria) this;
        }

        public Criteria andBasicpricenotesGreaterThanOrEqualTo(String value) {
            addCriterion("basicpricenotes >=", value, "basicpricenotes");
            return (Criteria) this;
        }

        public Criteria andBasicpricenotesLessThan(String value) {
            addCriterion("basicpricenotes <", value, "basicpricenotes");
            return (Criteria) this;
        }

        public Criteria andBasicpricenotesLessThanOrEqualTo(String value) {
            addCriterion("basicpricenotes <=", value, "basicpricenotes");
            return (Criteria) this;
        }

        public Criteria andBasicpricenotesLike(String value) {
            addCriterion("basicpricenotes like", value, "basicpricenotes");
            return (Criteria) this;
        }

        public Criteria andBasicpricenotesNotLike(String value) {
            addCriterion("basicpricenotes not like", value, "basicpricenotes");
            return (Criteria) this;
        }

        public Criteria andBasicpricenotesIn(List<String> values) {
            addCriterion("basicpricenotes in", values, "basicpricenotes");
            return (Criteria) this;
        }

        public Criteria andBasicpricenotesNotIn(List<String> values) {
            addCriterion("basicpricenotes not in", values, "basicpricenotes");
            return (Criteria) this;
        }

        public Criteria andBasicpricenotesBetween(String value1, String value2) {
            addCriterion("basicpricenotes between", value1, value2, "basicpricenotes");
            return (Criteria) this;
        }

        public Criteria andBasicpricenotesNotBetween(String value1, String value2) {
            addCriterion("basicpricenotes not between", value1, value2, "basicpricenotes");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andInvestprojcodeIsNull() {
            addCriterion("investprojcode is null");
            return (Criteria) this;
        }

        public Criteria andInvestprojcodeIsNotNull() {
            addCriterion("investprojcode is not null");
            return (Criteria) this;
        }

        public Criteria andInvestprojcodeEqualTo(String value) {
            addCriterion("investprojcode =", value, "investprojcode");
            return (Criteria) this;
        }

        public Criteria andInvestprojcodeNotEqualTo(String value) {
            addCriterion("investprojcode <>", value, "investprojcode");
            return (Criteria) this;
        }

        public Criteria andInvestprojcodeGreaterThan(String value) {
            addCriterion("investprojcode >", value, "investprojcode");
            return (Criteria) this;
        }

        public Criteria andInvestprojcodeGreaterThanOrEqualTo(String value) {
            addCriterion("investprojcode >=", value, "investprojcode");
            return (Criteria) this;
        }

        public Criteria andInvestprojcodeLessThan(String value) {
            addCriterion("investprojcode <", value, "investprojcode");
            return (Criteria) this;
        }

        public Criteria andInvestprojcodeLessThanOrEqualTo(String value) {
            addCriterion("investprojcode <=", value, "investprojcode");
            return (Criteria) this;
        }

        public Criteria andInvestprojcodeLike(String value) {
            addCriterion("investprojcode like", value, "investprojcode");
            return (Criteria) this;
        }

        public Criteria andInvestprojcodeNotLike(String value) {
            addCriterion("investprojcode not like", value, "investprojcode");
            return (Criteria) this;
        }

        public Criteria andInvestprojcodeIn(List<String> values) {
            addCriterion("investprojcode in", values, "investprojcode");
            return (Criteria) this;
        }

        public Criteria andInvestprojcodeNotIn(List<String> values) {
            addCriterion("investprojcode not in", values, "investprojcode");
            return (Criteria) this;
        }

        public Criteria andInvestprojcodeBetween(String value1, String value2) {
            addCriterion("investprojcode between", value1, value2, "investprojcode");
            return (Criteria) this;
        }

        public Criteria andInvestprojcodeNotBetween(String value1, String value2) {
            addCriterion("investprojcode not between", value1, value2, "investprojcode");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIsContractIsNull() {
            addCriterion("isContract is null");
            return (Criteria) this;
        }

        public Criteria andIsContractIsNotNull() {
            addCriterion("isContract is not null");
            return (Criteria) this;
        }

        public Criteria andIsContractEqualTo(Boolean value) {
            addCriterion("isContract =", value, "isContract");
            return (Criteria) this;
        }

        public Criteria andIsContractNotEqualTo(Boolean value) {
            addCriterion("isContract <>", value, "isContract");
            return (Criteria) this;
        }

        public Criteria andIsContractGreaterThan(Boolean value) {
            addCriterion("isContract >", value, "isContract");
            return (Criteria) this;
        }

        public Criteria andIsContractGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isContract >=", value, "isContract");
            return (Criteria) this;
        }

        public Criteria andIsContractLessThan(Boolean value) {
            addCriterion("isContract <", value, "isContract");
            return (Criteria) this;
        }

        public Criteria andIsContractLessThanOrEqualTo(Boolean value) {
            addCriterion("isContract <=", value, "isContract");
            return (Criteria) this;
        }

        public Criteria andIsContractIn(List<Boolean> values) {
            addCriterion("isContract in", values, "isContract");
            return (Criteria) this;
        }

        public Criteria andIsContractNotIn(List<Boolean> values) {
            addCriterion("isContract not in", values, "isContract");
            return (Criteria) this;
        }

        public Criteria andIsContractBetween(Boolean value1, Boolean value2) {
            addCriterion("isContract between", value1, value2, "isContract");
            return (Criteria) this;
        }

        public Criteria andIsContractNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isContract not between", value1, value2, "isContract");
            return (Criteria) this;
        }

        public Criteria andIsPublishIsNull() {
            addCriterion("isPublish is null");
            return (Criteria) this;
        }

        public Criteria andIsPublishIsNotNull() {
            addCriterion("isPublish is not null");
            return (Criteria) this;
        }

        public Criteria andIsPublishEqualTo(Boolean value) {
            addCriterion("isPublish =", value, "isPublish");
            return (Criteria) this;
        }

        public Criteria andIsPublishNotEqualTo(Boolean value) {
            addCriterion("isPublish <>", value, "isPublish");
            return (Criteria) this;
        }

        public Criteria andIsPublishGreaterThan(Boolean value) {
            addCriterion("isPublish >", value, "isPublish");
            return (Criteria) this;
        }

        public Criteria andIsPublishGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isPublish >=", value, "isPublish");
            return (Criteria) this;
        }

        public Criteria andIsPublishLessThan(Boolean value) {
            addCriterion("isPublish <", value, "isPublish");
            return (Criteria) this;
        }

        public Criteria andIsPublishLessThanOrEqualTo(Boolean value) {
            addCriterion("isPublish <=", value, "isPublish");
            return (Criteria) this;
        }

        public Criteria andIsPublishIn(List<Boolean> values) {
            addCriterion("isPublish in", values, "isPublish");
            return (Criteria) this;
        }

        public Criteria andIsPublishNotIn(List<Boolean> values) {
            addCriterion("isPublish not in", values, "isPublish");
            return (Criteria) this;
        }

        public Criteria andIsPublishBetween(Boolean value1, Boolean value2) {
            addCriterion("isPublish between", value1, value2, "isPublish");
            return (Criteria) this;
        }

        public Criteria andIsPublishNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isPublish not between", value1, value2, "isPublish");
            return (Criteria) this;
        }

        public Criteria andIsCexpertIsNull() {
            addCriterion("isCexpert is null");
            return (Criteria) this;
        }

        public Criteria andIsCexpertIsNotNull() {
            addCriterion("isCexpert is not null");
            return (Criteria) this;
        }

        public Criteria andIsCexpertEqualTo(Boolean value) {
            addCriterion("isCexpert =", value, "isCexpert");
            return (Criteria) this;
        }

        public Criteria andIsCexpertNotEqualTo(Boolean value) {
            addCriterion("isCexpert <>", value, "isCexpert");
            return (Criteria) this;
        }

        public Criteria andIsCexpertGreaterThan(Boolean value) {
            addCriterion("isCexpert >", value, "isCexpert");
            return (Criteria) this;
        }

        public Criteria andIsCexpertGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isCexpert >=", value, "isCexpert");
            return (Criteria) this;
        }

        public Criteria andIsCexpertLessThan(Boolean value) {
            addCriterion("isCexpert <", value, "isCexpert");
            return (Criteria) this;
        }

        public Criteria andIsCexpertLessThanOrEqualTo(Boolean value) {
            addCriterion("isCexpert <=", value, "isCexpert");
            return (Criteria) this;
        }

        public Criteria andIsCexpertIn(List<Boolean> values) {
            addCriterion("isCexpert in", values, "isCexpert");
            return (Criteria) this;
        }

        public Criteria andIsCexpertNotIn(List<Boolean> values) {
            addCriterion("isCexpert not in", values, "isCexpert");
            return (Criteria) this;
        }

        public Criteria andIsCexpertBetween(Boolean value1, Boolean value2) {
            addCriterion("isCexpert between", value1, value2, "isCexpert");
            return (Criteria) this;
        }

        public Criteria andIsCexpertNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isCexpert not between", value1, value2, "isCexpert");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table section
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table section
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}