package com.bizwink.po;

import java.util.Date;

public class SuppBiddingRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.purchaseprojcode
     *
     * @mbggenerated
     */
    private String purchaseprojcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.xcProjectCode
     *
     * @mbggenerated
     */
    private String xcProjectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.biddername
     *
     * @mbggenerated
     */
    private String biddername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Biddercode
     *
     * @mbggenerated
     */
    private String biddercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Contactor
     *
     * @mbggenerated
     */
    private String contactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Mphone
     *
     * @mbggenerated
     */
    private String mphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.deliveryDatetime
     *
     * @mbggenerated
     */
    private Date deliveryDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Sealsstatus
     *
     * @mbggenerated
     */
    private String sealsstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Hasreceipt
     *
     * @mbggenerated
     */
    private String hasreceipt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Notes
     *
     * @mbggenerated
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Attachment
     *
     * @mbggenerated
     */
    private String attachment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Isreject
     *
     * @mbggenerated
     */
    private String isreject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Rejectbrief
     *
     * @mbggenerated
     */
    private String rejectbrief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Platformcode
     *
     * @mbggenerated
     */
    private String platformcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Placecode
     *
     * @mbggenerated
     */
    private String placecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Pubserviceplatcode
     *
     * @mbggenerated
     */
    private String pubserviceplatcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Customer
     *
     * @mbggenerated
     */
    private String customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.CreateTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.UpdateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.Modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.taskBookId
     *
     * @mbggenerated
     */
    private String taskBookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supp_bidding_record.castSection
     *
     * @mbggenerated
     */
    private String castSection;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.uuid
     *
     * @return the value of supp_bidding_record.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.uuid
     *
     * @param uuid the value for supp_bidding_record.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.purchaseprojcode
     *
     * @return the value of supp_bidding_record.purchaseprojcode
     *
     * @mbggenerated
     */
    public String getPurchaseprojcode() {
        return purchaseprojcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.purchaseprojcode
     *
     * @param purchaseprojcode the value for supp_bidding_record.purchaseprojcode
     *
     * @mbggenerated
     */
    public void setPurchaseprojcode(String purchaseprojcode) {
        this.purchaseprojcode = purchaseprojcode == null ? null : purchaseprojcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.xcProjectCode
     *
     * @return the value of supp_bidding_record.xcProjectCode
     *
     * @mbggenerated
     */
    public String getXcProjectCode() {
        return xcProjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.xcProjectCode
     *
     * @param xcProjectCode the value for supp_bidding_record.xcProjectCode
     *
     * @mbggenerated
     */
    public void setXcProjectCode(String xcProjectCode) {
        this.xcProjectCode = xcProjectCode == null ? null : xcProjectCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.biddername
     *
     * @return the value of supp_bidding_record.biddername
     *
     * @mbggenerated
     */
    public String getBiddername() {
        return biddername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.biddername
     *
     * @param biddername the value for supp_bidding_record.biddername
     *
     * @mbggenerated
     */
    public void setBiddername(String biddername) {
        this.biddername = biddername == null ? null : biddername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Biddercode
     *
     * @return the value of supp_bidding_record.Biddercode
     *
     * @mbggenerated
     */
    public String getBiddercode() {
        return biddercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Biddercode
     *
     * @param biddercode the value for supp_bidding_record.Biddercode
     *
     * @mbggenerated
     */
    public void setBiddercode(String biddercode) {
        this.biddercode = biddercode == null ? null : biddercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Contactor
     *
     * @return the value of supp_bidding_record.Contactor
     *
     * @mbggenerated
     */
    public String getContactor() {
        return contactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Contactor
     *
     * @param contactor the value for supp_bidding_record.Contactor
     *
     * @mbggenerated
     */
    public void setContactor(String contactor) {
        this.contactor = contactor == null ? null : contactor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Mphone
     *
     * @return the value of supp_bidding_record.Mphone
     *
     * @mbggenerated
     */
    public String getMphone() {
        return mphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Mphone
     *
     * @param mphone the value for supp_bidding_record.Mphone
     *
     * @mbggenerated
     */
    public void setMphone(String mphone) {
        this.mphone = mphone == null ? null : mphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.deliveryDatetime
     *
     * @return the value of supp_bidding_record.deliveryDatetime
     *
     * @mbggenerated
     */
    public Date getDeliveryDatetime() {
        return deliveryDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.deliveryDatetime
     *
     * @param deliveryDatetime the value for supp_bidding_record.deliveryDatetime
     *
     * @mbggenerated
     */
    public void setDeliveryDatetime(Date deliveryDatetime) {
        this.deliveryDatetime = deliveryDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Sealsstatus
     *
     * @return the value of supp_bidding_record.Sealsstatus
     *
     * @mbggenerated
     */
    public String getSealsstatus() {
        return sealsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Sealsstatus
     *
     * @param sealsstatus the value for supp_bidding_record.Sealsstatus
     *
     * @mbggenerated
     */
    public void setSealsstatus(String sealsstatus) {
        this.sealsstatus = sealsstatus == null ? null : sealsstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Hasreceipt
     *
     * @return the value of supp_bidding_record.Hasreceipt
     *
     * @mbggenerated
     */
    public String getHasreceipt() {
        return hasreceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Hasreceipt
     *
     * @param hasreceipt the value for supp_bidding_record.Hasreceipt
     *
     * @mbggenerated
     */
    public void setHasreceipt(String hasreceipt) {
        this.hasreceipt = hasreceipt == null ? null : hasreceipt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Notes
     *
     * @return the value of supp_bidding_record.Notes
     *
     * @mbggenerated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Notes
     *
     * @param notes the value for supp_bidding_record.Notes
     *
     * @mbggenerated
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Attachment
     *
     * @return the value of supp_bidding_record.Attachment
     *
     * @mbggenerated
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Attachment
     *
     * @param attachment the value for supp_bidding_record.Attachment
     *
     * @mbggenerated
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Isreject
     *
     * @return the value of supp_bidding_record.Isreject
     *
     * @mbggenerated
     */
    public String getIsreject() {
        return isreject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Isreject
     *
     * @param isreject the value for supp_bidding_record.Isreject
     *
     * @mbggenerated
     */
    public void setIsreject(String isreject) {
        this.isreject = isreject == null ? null : isreject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Rejectbrief
     *
     * @return the value of supp_bidding_record.Rejectbrief
     *
     * @mbggenerated
     */
    public String getRejectbrief() {
        return rejectbrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Rejectbrief
     *
     * @param rejectbrief the value for supp_bidding_record.Rejectbrief
     *
     * @mbggenerated
     */
    public void setRejectbrief(String rejectbrief) {
        this.rejectbrief = rejectbrief == null ? null : rejectbrief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Platformcode
     *
     * @return the value of supp_bidding_record.Platformcode
     *
     * @mbggenerated
     */
    public String getPlatformcode() {
        return platformcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Platformcode
     *
     * @param platformcode the value for supp_bidding_record.Platformcode
     *
     * @mbggenerated
     */
    public void setPlatformcode(String platformcode) {
        this.platformcode = platformcode == null ? null : platformcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Placecode
     *
     * @return the value of supp_bidding_record.Placecode
     *
     * @mbggenerated
     */
    public String getPlacecode() {
        return placecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Placecode
     *
     * @param placecode the value for supp_bidding_record.Placecode
     *
     * @mbggenerated
     */
    public void setPlacecode(String placecode) {
        this.placecode = placecode == null ? null : placecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Pubserviceplatcode
     *
     * @return the value of supp_bidding_record.Pubserviceplatcode
     *
     * @mbggenerated
     */
    public String getPubserviceplatcode() {
        return pubserviceplatcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Pubserviceplatcode
     *
     * @param pubserviceplatcode the value for supp_bidding_record.Pubserviceplatcode
     *
     * @mbggenerated
     */
    public void setPubserviceplatcode(String pubserviceplatcode) {
        this.pubserviceplatcode = pubserviceplatcode == null ? null : pubserviceplatcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Customer
     *
     * @return the value of supp_bidding_record.Customer
     *
     * @mbggenerated
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Customer
     *
     * @param customer the value for supp_bidding_record.Customer
     *
     * @mbggenerated
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.CreateTime
     *
     * @return the value of supp_bidding_record.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.CreateTime
     *
     * @param createTime the value for supp_bidding_record.CreateTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Creator
     *
     * @return the value of supp_bidding_record.Creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Creator
     *
     * @param creator the value for supp_bidding_record.Creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.UpdateTime
     *
     * @return the value of supp_bidding_record.UpdateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.UpdateTime
     *
     * @param updateTime the value for supp_bidding_record.UpdateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.Modifier
     *
     * @return the value of supp_bidding_record.Modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.Modifier
     *
     * @param modifier the value for supp_bidding_record.Modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.taskBookId
     *
     * @return the value of supp_bidding_record.taskBookId
     *
     * @mbggenerated
     */
    public String getTaskBookId() {
        return taskBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.taskBookId
     *
     * @param taskBookId the value for supp_bidding_record.taskBookId
     *
     * @mbggenerated
     */
    public void setTaskBookId(String taskBookId) {
        this.taskBookId = taskBookId == null ? null : taskBookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supp_bidding_record.castSection
     *
     * @return the value of supp_bidding_record.castSection
     *
     * @mbggenerated
     */
    public String getCastSection() {
        return castSection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supp_bidding_record.castSection
     *
     * @param castSection the value for supp_bidding_record.castSection
     *
     * @mbggenerated
     */
    public void setCastSection(String castSection) {
        this.castSection = castSection == null ? null : castSection.trim();
    }
}