package com.bizwink.po;

import java.math.BigDecimal;
import java.util.Date;

public class TrainingProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TRAININGPROJECT.ID
     *
     * @mbggenerated
     */
    private BigDecimal ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TRAININGPROJECT.PROJNAME
     *
     * @mbggenerated
     */
    private String PROJNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TRAININGPROJECT.PROJCODE
     *
     * @mbggenerated
     */
    private String PROJCODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TRAININGPROJECT.BRIEF
     *
     * @mbggenerated
     */
    private String BRIEF;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TRAININGPROJECT.CREATEDATE
     *
     * @mbggenerated
     */
    private Date CREATEDATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TRAININGPROJECT.ID
     *
     * @return the value of TBL_TRAININGPROJECT.ID
     *
     * @mbggenerated
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TRAININGPROJECT.ID
     *
     * @param ID the value for TBL_TRAININGPROJECT.ID
     *
     * @mbggenerated
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TRAININGPROJECT.PROJNAME
     *
     * @return the value of TBL_TRAININGPROJECT.PROJNAME
     *
     * @mbggenerated
     */
    public String getPROJNAME() {
        return PROJNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TRAININGPROJECT.PROJNAME
     *
     * @param PROJNAME the value for TBL_TRAININGPROJECT.PROJNAME
     *
     * @mbggenerated
     */
    public void setPROJNAME(String PROJNAME) {
        this.PROJNAME = PROJNAME == null ? null : PROJNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TRAININGPROJECT.PROJCODE
     *
     * @return the value of TBL_TRAININGPROJECT.PROJCODE
     *
     * @mbggenerated
     */
    public String getPROJCODE() {
        return PROJCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TRAININGPROJECT.PROJCODE
     *
     * @param PROJCODE the value for TBL_TRAININGPROJECT.PROJCODE
     *
     * @mbggenerated
     */
    public void setPROJCODE(String PROJCODE) {
        this.PROJCODE = PROJCODE == null ? null : PROJCODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TRAININGPROJECT.BRIEF
     *
     * @return the value of TBL_TRAININGPROJECT.BRIEF
     *
     * @mbggenerated
     */
    public String getBRIEF() {
        return BRIEF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TRAININGPROJECT.BRIEF
     *
     * @param BRIEF the value for TBL_TRAININGPROJECT.BRIEF
     *
     * @mbggenerated
     */
    public void setBRIEF(String BRIEF) {
        this.BRIEF = BRIEF == null ? null : BRIEF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TRAININGPROJECT.CREATEDATE
     *
     * @return the value of TBL_TRAININGPROJECT.CREATEDATE
     *
     * @mbggenerated
     */
    public Date getCREATEDATE() {
        return CREATEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TRAININGPROJECT.CREATEDATE
     *
     * @param CREATEDATE the value for TBL_TRAININGPROJECT.CREATEDATE
     *
     * @mbggenerated
     */
    public void setCREATEDATE(Date CREATEDATE) {
        this.CREATEDATE = CREATEDATE;
    }
}