package com.bizwink.po;

public class WinResultsNoticeWithBLOBs extends WinResultsNotice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column win_results_notice.purchaseprojUsing
     *
     * @mbggenerated
     */
    private String purchaseprojUsing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column win_results_notice.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column win_results_notice.serviceContent
     *
     * @mbggenerated
     */
    private String serviceContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column win_results_notice.winBidRate
     *
     * @mbggenerated
     */
    private String winBidRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column win_results_notice.notes
     *
     * @mbggenerated
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column win_results_notice.richTextContent
     *
     * @mbggenerated
     */
    private String richTextContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column win_results_notice.purchaseprojUsing
     *
     * @return the value of win_results_notice.purchaseprojUsing
     *
     * @mbggenerated
     */
    public String getPurchaseprojUsing() {
        return purchaseprojUsing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column win_results_notice.purchaseprojUsing
     *
     * @param purchaseprojUsing the value for win_results_notice.purchaseprojUsing
     *
     * @mbggenerated
     */
    public void setPurchaseprojUsing(String purchaseprojUsing) {
        this.purchaseprojUsing = purchaseprojUsing == null ? null : purchaseprojUsing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column win_results_notice.content
     *
     * @return the value of win_results_notice.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column win_results_notice.content
     *
     * @param content the value for win_results_notice.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column win_results_notice.serviceContent
     *
     * @return the value of win_results_notice.serviceContent
     *
     * @mbggenerated
     */
    public String getServiceContent() {
        return serviceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column win_results_notice.serviceContent
     *
     * @param serviceContent the value for win_results_notice.serviceContent
     *
     * @mbggenerated
     */
    public void setServiceContent(String serviceContent) {
        this.serviceContent = serviceContent == null ? null : serviceContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column win_results_notice.winBidRate
     *
     * @return the value of win_results_notice.winBidRate
     *
     * @mbggenerated
     */
    public String getWinBidRate() {
        return winBidRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column win_results_notice.winBidRate
     *
     * @param winBidRate the value for win_results_notice.winBidRate
     *
     * @mbggenerated
     */
    public void setWinBidRate(String winBidRate) {
        this.winBidRate = winBidRate == null ? null : winBidRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column win_results_notice.notes
     *
     * @return the value of win_results_notice.notes
     *
     * @mbggenerated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column win_results_notice.notes
     *
     * @param notes the value for win_results_notice.notes
     *
     * @mbggenerated
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column win_results_notice.richTextContent
     *
     * @return the value of win_results_notice.richTextContent
     *
     * @mbggenerated
     */
    public String getRichTextContent() {
        return richTextContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column win_results_notice.richTextContent
     *
     * @param richTextContent the value for win_results_notice.richTextContent
     *
     * @mbggenerated
     */
    public void setRichTextContent(String richTextContent) {
        this.richTextContent = richTextContent == null ? null : richTextContent.trim();
    }
}