package com.bizwink.po;

import java.io.Serializable;
import java.util.Date;

public class CmClassapply  implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CLASS_APPLY.C_ID
     *
     * @mbggenerated
     */
    private Long c_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CLASS_APPLY.C_EXPLAIN
     *
     * @mbggenerated
     */
    private String c_EXPLAIN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CLASS_APPLY.C_CONTACTOR
     *
     * @mbggenerated
     */
    private String c_CONTACTOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CLASS_APPLY.C_MOBILE
     *
     * @mbggenerated
     */
    private String c_MOBILE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CLASS_APPLY.C_CREATE_USER
     *
     * @mbggenerated
     */
    private Long c_CREATE_USER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CLASS_APPLY.C_CREATE_COMP
     *
     * @mbggenerated
     */
    private Long c_CREATE_COMP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CLASS_APPLY.C_CREATE_DATE
     *
     * @mbggenerated
     */
    private Date c_CREATE_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CLASS_APPLY.C_CUSTOMER
     *
     * @mbggenerated
     */
    private Long c_CUSTOMER;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CLASS_APPLY.C_ID
     *
     * @return the value of T_CM_CLASS_APPLY.C_ID
     *
     * @mbggenerated
     */
    public Long getC_ID() {
        return c_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CLASS_APPLY.C_ID
     *
     * @param c_ID the value for T_CM_CLASS_APPLY.C_ID
     *
     * @mbggenerated
     */
    public void setC_ID(Long c_ID) {
        this.c_ID = c_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CLASS_APPLY.C_EXPLAIN
     *
     * @return the value of T_CM_CLASS_APPLY.C_EXPLAIN
     *
     * @mbggenerated
     */
    public String getC_EXPLAIN() {
        return c_EXPLAIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CLASS_APPLY.C_EXPLAIN
     *
     * @param c_EXPLAIN the value for T_CM_CLASS_APPLY.C_EXPLAIN
     *
     * @mbggenerated
     */
    public void setC_EXPLAIN(String c_EXPLAIN) {
        this.c_EXPLAIN = c_EXPLAIN == null ? null : c_EXPLAIN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CLASS_APPLY.C_CONTACTOR
     *
     * @return the value of T_CM_CLASS_APPLY.C_CONTACTOR
     *
     * @mbggenerated
     */
    public String getC_CONTACTOR() {
        return c_CONTACTOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CLASS_APPLY.C_CONTACTOR
     *
     * @param c_CONTACTOR the value for T_CM_CLASS_APPLY.C_CONTACTOR
     *
     * @mbggenerated
     */
    public void setC_CONTACTOR(String c_CONTACTOR) {
        this.c_CONTACTOR = c_CONTACTOR == null ? null : c_CONTACTOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CLASS_APPLY.C_MOBILE
     *
     * @return the value of T_CM_CLASS_APPLY.C_MOBILE
     *
     * @mbggenerated
     */
    public String getC_MOBILE() {
        return c_MOBILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CLASS_APPLY.C_MOBILE
     *
     * @param c_MOBILE the value for T_CM_CLASS_APPLY.C_MOBILE
     *
     * @mbggenerated
     */
    public void setC_MOBILE(String c_MOBILE) {
        this.c_MOBILE = c_MOBILE == null ? null : c_MOBILE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CLASS_APPLY.C_CREATE_USER
     *
     * @return the value of T_CM_CLASS_APPLY.C_CREATE_USER
     *
     * @mbggenerated
     */
    public Long getC_CREATE_USER() {
        return c_CREATE_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CLASS_APPLY.C_CREATE_USER
     *
     * @param c_CREATE_USER the value for T_CM_CLASS_APPLY.C_CREATE_USER
     *
     * @mbggenerated
     */
    public void setC_CREATE_USER(Long c_CREATE_USER) {
        this.c_CREATE_USER = c_CREATE_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CLASS_APPLY.C_CREATE_COMP
     *
     * @return the value of T_CM_CLASS_APPLY.C_CREATE_COMP
     *
     * @mbggenerated
     */
    public Long getC_CREATE_COMP() {
        return c_CREATE_COMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CLASS_APPLY.C_CREATE_COMP
     *
     * @param c_CREATE_COMP the value for T_CM_CLASS_APPLY.C_CREATE_COMP
     *
     * @mbggenerated
     */
    public void setC_CREATE_COMP(Long c_CREATE_COMP) {
        this.c_CREATE_COMP = c_CREATE_COMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CLASS_APPLY.C_CREATE_DATE
     *
     * @return the value of T_CM_CLASS_APPLY.C_CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getC_CREATE_DATE() {
        return c_CREATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CLASS_APPLY.C_CREATE_DATE
     *
     * @param c_CREATE_DATE the value for T_CM_CLASS_APPLY.C_CREATE_DATE
     *
     * @mbggenerated
     */
    public void setC_CREATE_DATE(Date c_CREATE_DATE) {
        this.c_CREATE_DATE = c_CREATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CLASS_APPLY.C_CUSTOMER
     *
     * @return the value of T_CM_CLASS_APPLY.C_CUSTOMER
     *
     * @mbggenerated
     */
    public Long getC_CUSTOMER() {
        return c_CUSTOMER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CLASS_APPLY.C_CUSTOMER
     *
     * @param c_CUSTOMER the value for T_CM_CLASS_APPLY.C_CUSTOMER
     *
     * @mbggenerated
     */
    public void setC_CUSTOMER(Long c_CUSTOMER) {
        this.c_CUSTOMER = c_CUSTOMER;
    }
}