package com.bizwink.po;

import java.io.Serializable;
import java.util.Date;

public class CmCodevalue implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_ID
     *
     * @mbggenerated
     */
    private Long c_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_M_CODE
     *
     * @mbggenerated
     */
    private String c_M_CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_M_NAME
     *
     * @mbggenerated
     */
    private String c_M_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_CLASS_ID
     *
     * @mbggenerated
     */
    private Long c_CLASS_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_CLASS_CODE
     *
     * @mbggenerated
     */
    private String c_CLASS_CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_MODEL_NUMBER
     *
     * @mbggenerated
     */
    private String c_MODEL_NUMBER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_UNIT
     *
     * @mbggenerated
     */
    private String c_UNIT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_KEYWORDS
     *
     * @mbggenerated
     */
    private String c_KEYWORDS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_STATUS
     *
     * @mbggenerated
     */
    private Short c_STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_DESC
     *
     * @mbggenerated
     */
    private String c_DESC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_IS_TEMP
     *
     * @mbggenerated
     */
    private Short c_IS_TEMP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_ORDER_BY
     *
     * @mbggenerated
     */
    private Short c_ORDER_BY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_HAS_TRANSACTION
     *
     * @mbggenerated
     */
    private Short c_HAS_TRANSACTION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_CREATE_USER
     *
     * @mbggenerated
     */
    private Long c_CREATE_USER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_CREATE_COMP
     *
     * @mbggenerated
     */
    private Long c_CREATE_COMP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_CREATE_DATE
     *
     * @mbggenerated
     */
    private Date c_CREATE_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_CUSTOMER
     *
     * @mbggenerated
     */
    private Long c_CUSTOMER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_DELETE_FLAG
     *
     * @mbggenerated
     */
    private Short c_DELETE_FLAG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CM_CODE_VALUE.C_EXPLAIN
     *
     * @mbggenerated
     */
    private String c_EXPLAIN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_ID
     *
     * @return the value of T_CM_CODE_VALUE.C_ID
     *
     * @mbggenerated
     */
    public Long getC_ID() {
        return c_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_ID
     *
     * @param c_ID the value for T_CM_CODE_VALUE.C_ID
     *
     * @mbggenerated
     */
    public void setC_ID(Long c_ID) {
        this.c_ID = c_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_M_CODE
     *
     * @return the value of T_CM_CODE_VALUE.C_M_CODE
     *
     * @mbggenerated
     */
    public String getC_M_CODE() {
        return c_M_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_M_CODE
     *
     * @param c_M_CODE the value for T_CM_CODE_VALUE.C_M_CODE
     *
     * @mbggenerated
     */
    public void setC_M_CODE(String c_M_CODE) {
        this.c_M_CODE = c_M_CODE == null ? null : c_M_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_M_NAME
     *
     * @return the value of T_CM_CODE_VALUE.C_M_NAME
     *
     * @mbggenerated
     */
    public String getC_M_NAME() {
        return c_M_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_M_NAME
     *
     * @param c_M_NAME the value for T_CM_CODE_VALUE.C_M_NAME
     *
     * @mbggenerated
     */
    public void setC_M_NAME(String c_M_NAME) {
        this.c_M_NAME = c_M_NAME == null ? null : c_M_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_CLASS_ID
     *
     * @return the value of T_CM_CODE_VALUE.C_CLASS_ID
     *
     * @mbggenerated
     */
    public Long getC_CLASS_ID() {
        return c_CLASS_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_CLASS_ID
     *
     * @param c_CLASS_ID the value for T_CM_CODE_VALUE.C_CLASS_ID
     *
     * @mbggenerated
     */
    public void setC_CLASS_ID(Long c_CLASS_ID) {
        this.c_CLASS_ID = c_CLASS_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_CLASS_CODE
     *
     * @return the value of T_CM_CODE_VALUE.C_CLASS_CODE
     *
     * @mbggenerated
     */
    public String getC_CLASS_CODE() {
        return c_CLASS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_CLASS_CODE
     *
     * @param c_CLASS_CODE the value for T_CM_CODE_VALUE.C_CLASS_CODE
     *
     * @mbggenerated
     */
    public void setC_CLASS_CODE(String c_CLASS_CODE) {
        this.c_CLASS_CODE = c_CLASS_CODE == null ? null : c_CLASS_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_MODEL_NUMBER
     *
     * @return the value of T_CM_CODE_VALUE.C_MODEL_NUMBER
     *
     * @mbggenerated
     */
    public String getC_MODEL_NUMBER() {
        return c_MODEL_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_MODEL_NUMBER
     *
     * @param c_MODEL_NUMBER the value for T_CM_CODE_VALUE.C_MODEL_NUMBER
     *
     * @mbggenerated
     */
    public void setC_MODEL_NUMBER(String c_MODEL_NUMBER) {
        this.c_MODEL_NUMBER = c_MODEL_NUMBER == null ? null : c_MODEL_NUMBER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_UNIT
     *
     * @return the value of T_CM_CODE_VALUE.C_UNIT
     *
     * @mbggenerated
     */
    public String getC_UNIT() {
        return c_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_UNIT
     *
     * @param c_UNIT the value for T_CM_CODE_VALUE.C_UNIT
     *
     * @mbggenerated
     */
    public void setC_UNIT(String c_UNIT) {
        this.c_UNIT = c_UNIT == null ? null : c_UNIT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_KEYWORDS
     *
     * @return the value of T_CM_CODE_VALUE.C_KEYWORDS
     *
     * @mbggenerated
     */
    public String getC_KEYWORDS() {
        return c_KEYWORDS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_KEYWORDS
     *
     * @param c_KEYWORDS the value for T_CM_CODE_VALUE.C_KEYWORDS
     *
     * @mbggenerated
     */
    public void setC_KEYWORDS(String c_KEYWORDS) {
        this.c_KEYWORDS = c_KEYWORDS == null ? null : c_KEYWORDS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_STATUS
     *
     * @return the value of T_CM_CODE_VALUE.C_STATUS
     *
     * @mbggenerated
     */
    public Short getC_STATUS() {
        return c_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_STATUS
     *
     * @param c_STATUS the value for T_CM_CODE_VALUE.C_STATUS
     *
     * @mbggenerated
     */
    public void setC_STATUS(Short c_STATUS) {
        this.c_STATUS = c_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_DESC
     *
     * @return the value of T_CM_CODE_VALUE.C_DESC
     *
     * @mbggenerated
     */
    public String getC_DESC() {
        return c_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_DESC
     *
     * @param c_DESC the value for T_CM_CODE_VALUE.C_DESC
     *
     * @mbggenerated
     */
    public void setC_DESC(String c_DESC) {
        this.c_DESC = c_DESC == null ? null : c_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_IS_TEMP
     *
     * @return the value of T_CM_CODE_VALUE.C_IS_TEMP
     *
     * @mbggenerated
     */
    public Short getC_IS_TEMP() {
        return c_IS_TEMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_IS_TEMP
     *
     * @param c_IS_TEMP the value for T_CM_CODE_VALUE.C_IS_TEMP
     *
     * @mbggenerated
     */
    public void setC_IS_TEMP(Short c_IS_TEMP) {
        this.c_IS_TEMP = c_IS_TEMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_ORDER_BY
     *
     * @return the value of T_CM_CODE_VALUE.C_ORDER_BY
     *
     * @mbggenerated
     */
    public Short getC_ORDER_BY() {
        return c_ORDER_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_ORDER_BY
     *
     * @param c_ORDER_BY the value for T_CM_CODE_VALUE.C_ORDER_BY
     *
     * @mbggenerated
     */
    public void setC_ORDER_BY(Short c_ORDER_BY) {
        this.c_ORDER_BY = c_ORDER_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_HAS_TRANSACTION
     *
     * @return the value of T_CM_CODE_VALUE.C_HAS_TRANSACTION
     *
     * @mbggenerated
     */
    public Short getC_HAS_TRANSACTION() {
        return c_HAS_TRANSACTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_HAS_TRANSACTION
     *
     * @param c_HAS_TRANSACTION the value for T_CM_CODE_VALUE.C_HAS_TRANSACTION
     *
     * @mbggenerated
     */
    public void setC_HAS_TRANSACTION(Short c_HAS_TRANSACTION) {
        this.c_HAS_TRANSACTION = c_HAS_TRANSACTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_CREATE_USER
     *
     * @return the value of T_CM_CODE_VALUE.C_CREATE_USER
     *
     * @mbggenerated
     */
    public Long getC_CREATE_USER() {
        return c_CREATE_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_CREATE_USER
     *
     * @param c_CREATE_USER the value for T_CM_CODE_VALUE.C_CREATE_USER
     *
     * @mbggenerated
     */
    public void setC_CREATE_USER(Long c_CREATE_USER) {
        this.c_CREATE_USER = c_CREATE_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_CREATE_COMP
     *
     * @return the value of T_CM_CODE_VALUE.C_CREATE_COMP
     *
     * @mbggenerated
     */
    public Long getC_CREATE_COMP() {
        return c_CREATE_COMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_CREATE_COMP
     *
     * @param c_CREATE_COMP the value for T_CM_CODE_VALUE.C_CREATE_COMP
     *
     * @mbggenerated
     */
    public void setC_CREATE_COMP(Long c_CREATE_COMP) {
        this.c_CREATE_COMP = c_CREATE_COMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_CREATE_DATE
     *
     * @return the value of T_CM_CODE_VALUE.C_CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getC_CREATE_DATE() {
        return c_CREATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_CREATE_DATE
     *
     * @param c_CREATE_DATE the value for T_CM_CODE_VALUE.C_CREATE_DATE
     *
     * @mbggenerated
     */
    public void setC_CREATE_DATE(Date c_CREATE_DATE) {
        this.c_CREATE_DATE = c_CREATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_CUSTOMER
     *
     * @return the value of T_CM_CODE_VALUE.C_CUSTOMER
     *
     * @mbggenerated
     */
    public Long getC_CUSTOMER() {
        return c_CUSTOMER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_CUSTOMER
     *
     * @param c_CUSTOMER the value for T_CM_CODE_VALUE.C_CUSTOMER
     *
     * @mbggenerated
     */
    public void setC_CUSTOMER(Long c_CUSTOMER) {
        this.c_CUSTOMER = c_CUSTOMER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_DELETE_FLAG
     *
     * @return the value of T_CM_CODE_VALUE.C_DELETE_FLAG
     *
     * @mbggenerated
     */
    public Short getC_DELETE_FLAG() {
        return c_DELETE_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_DELETE_FLAG
     *
     * @param c_DELETE_FLAG the value for T_CM_CODE_VALUE.C_DELETE_FLAG
     *
     * @mbggenerated
     */
    public void setC_DELETE_FLAG(Short c_DELETE_FLAG) {
        this.c_DELETE_FLAG = c_DELETE_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CM_CODE_VALUE.C_EXPLAIN
     *
     * @return the value of T_CM_CODE_VALUE.C_EXPLAIN
     *
     * @mbggenerated
     */
    public String getC_EXPLAIN() {
        return c_EXPLAIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CM_CODE_VALUE.C_EXPLAIN
     *
     * @param c_EXPLAIN the value for T_CM_CODE_VALUE.C_EXPLAIN
     *
     * @mbggenerated
     */
    public void setC_EXPLAIN(String c_EXPLAIN) {
        this.c_EXPLAIN = c_EXPLAIN == null ? null : c_EXPLAIN.trim();
    }
}