package com.bizwink.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ReserveExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    public ReserveExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSiteidIsNull() {
            addCriterion("SITEID is null");
            return (Criteria) this;
        }

        public Criteria andSiteidIsNotNull() {
            addCriterion("SITEID is not null");
            return (Criteria) this;
        }

        public Criteria andSiteidEqualTo(BigDecimal value) {
            addCriterion("SITEID =", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidNotEqualTo(BigDecimal value) {
            addCriterion("SITEID <>", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidGreaterThan(BigDecimal value) {
            addCriterion("SITEID >", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SITEID >=", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidLessThan(BigDecimal value) {
            addCriterion("SITEID <", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SITEID <=", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidIn(List<BigDecimal> values) {
            addCriterion("SITEID in", values, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidNotIn(List<BigDecimal> values) {
            addCriterion("SITEID not in", values, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SITEID between", value1, value2, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SITEID not between", value1, value2, "siteid");
            return (Criteria) this;
        }

        public Criteria andUsedateIsNull() {
            addCriterion("USEDATE is null");
            return (Criteria) this;
        }

        public Criteria andUsedateIsNotNull() {
            addCriterion("USEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andUsedateEqualTo(Date value) {
            addCriterionForJDBCDate("USEDATE =", value, "usedate");
            return (Criteria) this;
        }

        public Criteria andUsedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("USEDATE <>", value, "usedate");
            return (Criteria) this;
        }

        public Criteria andUsedateGreaterThan(Date value) {
            addCriterionForJDBCDate("USEDATE >", value, "usedate");
            return (Criteria) this;
        }

        public Criteria andUsedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("USEDATE >=", value, "usedate");
            return (Criteria) this;
        }

        public Criteria andUsedateLessThan(Date value) {
            addCriterionForJDBCDate("USEDATE <", value, "usedate");
            return (Criteria) this;
        }

        public Criteria andUsedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("USEDATE <=", value, "usedate");
            return (Criteria) this;
        }

        public Criteria andUsedateIn(List<Date> values) {
            addCriterionForJDBCDate("USEDATE in", values, "usedate");
            return (Criteria) this;
        }

        public Criteria andUsedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("USEDATE not in", values, "usedate");
            return (Criteria) this;
        }

        public Criteria andUsedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("USEDATE between", value1, value2, "usedate");
            return (Criteria) this;
        }

        public Criteria andUsedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("USEDATE not between", value1, value2, "usedate");
            return (Criteria) this;
        }

        public Criteria andNumemberIsNull() {
            addCriterion("NUMEMBER is null");
            return (Criteria) this;
        }

        public Criteria andNumemberIsNotNull() {
            addCriterion("NUMEMBER is not null");
            return (Criteria) this;
        }

        public Criteria andNumemberEqualTo(BigDecimal value) {
            addCriterion("NUMEMBER =", value, "numember");
            return (Criteria) this;
        }

        public Criteria andNumemberNotEqualTo(BigDecimal value) {
            addCriterion("NUMEMBER <>", value, "numember");
            return (Criteria) this;
        }

        public Criteria andNumemberGreaterThan(BigDecimal value) {
            addCriterion("NUMEMBER >", value, "numember");
            return (Criteria) this;
        }

        public Criteria andNumemberGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NUMEMBER >=", value, "numember");
            return (Criteria) this;
        }

        public Criteria andNumemberLessThan(BigDecimal value) {
            addCriterion("NUMEMBER <", value, "numember");
            return (Criteria) this;
        }

        public Criteria andNumemberLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NUMEMBER <=", value, "numember");
            return (Criteria) this;
        }

        public Criteria andNumemberIn(List<BigDecimal> values) {
            addCriterion("NUMEMBER in", values, "numember");
            return (Criteria) this;
        }

        public Criteria andNumemberNotIn(List<BigDecimal> values) {
            addCriterion("NUMEMBER not in", values, "numember");
            return (Criteria) this;
        }

        public Criteria andNumemberBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NUMEMBER between", value1, value2, "numember");
            return (Criteria) this;
        }

        public Criteria andNumemberNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NUMEMBER not between", value1, value2, "numember");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andMphoneIsNull() {
            addCriterion("MPHONE is null");
            return (Criteria) this;
        }

        public Criteria andMphoneIsNotNull() {
            addCriterion("MPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andMphoneEqualTo(String value) {
            addCriterion("MPHONE =", value, "mphone");
            return (Criteria) this;
        }

        public Criteria andMphoneNotEqualTo(String value) {
            addCriterion("MPHONE <>", value, "mphone");
            return (Criteria) this;
        }

        public Criteria andMphoneGreaterThan(String value) {
            addCriterion("MPHONE >", value, "mphone");
            return (Criteria) this;
        }

        public Criteria andMphoneGreaterThanOrEqualTo(String value) {
            addCriterion("MPHONE >=", value, "mphone");
            return (Criteria) this;
        }

        public Criteria andMphoneLessThan(String value) {
            addCriterion("MPHONE <", value, "mphone");
            return (Criteria) this;
        }

        public Criteria andMphoneLessThanOrEqualTo(String value) {
            addCriterion("MPHONE <=", value, "mphone");
            return (Criteria) this;
        }

        public Criteria andMphoneLike(String value) {
            addCriterion("MPHONE like", value, "mphone");
            return (Criteria) this;
        }

        public Criteria andMphoneNotLike(String value) {
            addCriterion("MPHONE not like", value, "mphone");
            return (Criteria) this;
        }

        public Criteria andMphoneIn(List<String> values) {
            addCriterion("MPHONE in", values, "mphone");
            return (Criteria) this;
        }

        public Criteria andMphoneNotIn(List<String> values) {
            addCriterion("MPHONE not in", values, "mphone");
            return (Criteria) this;
        }

        public Criteria andMphoneBetween(String value1, String value2) {
            addCriterion("MPHONE between", value1, value2, "mphone");
            return (Criteria) this;
        }

        public Criteria andMphoneNotBetween(String value1, String value2) {
            addCriterion("MPHONE not between", value1, value2, "mphone");
            return (Criteria) this;
        }

        public Criteria andLxrnameIsNull() {
            addCriterion("LXRNAME is null");
            return (Criteria) this;
        }

        public Criteria andLxrnameIsNotNull() {
            addCriterion("LXRNAME is not null");
            return (Criteria) this;
        }

        public Criteria andLxrnameEqualTo(String value) {
            addCriterion("LXRNAME =", value, "lxrname");
            return (Criteria) this;
        }

        public Criteria andLxrnameNotEqualTo(String value) {
            addCriterion("LXRNAME <>", value, "lxrname");
            return (Criteria) this;
        }

        public Criteria andLxrnameGreaterThan(String value) {
            addCriterion("LXRNAME >", value, "lxrname");
            return (Criteria) this;
        }

        public Criteria andLxrnameGreaterThanOrEqualTo(String value) {
            addCriterion("LXRNAME >=", value, "lxrname");
            return (Criteria) this;
        }

        public Criteria andLxrnameLessThan(String value) {
            addCriterion("LXRNAME <", value, "lxrname");
            return (Criteria) this;
        }

        public Criteria andLxrnameLessThanOrEqualTo(String value) {
            addCriterion("LXRNAME <=", value, "lxrname");
            return (Criteria) this;
        }

        public Criteria andLxrnameLike(String value) {
            addCriterion("LXRNAME like", value, "lxrname");
            return (Criteria) this;
        }

        public Criteria andLxrnameNotLike(String value) {
            addCriterion("LXRNAME not like", value, "lxrname");
            return (Criteria) this;
        }

        public Criteria andLxrnameIn(List<String> values) {
            addCriterion("LXRNAME in", values, "lxrname");
            return (Criteria) this;
        }

        public Criteria andLxrnameNotIn(List<String> values) {
            addCriterion("LXRNAME not in", values, "lxrname");
            return (Criteria) this;
        }

        public Criteria andLxrnameBetween(String value1, String value2) {
            addCriterion("LXRNAME between", value1, value2, "lxrname");
            return (Criteria) this;
        }

        public Criteria andLxrnameNotBetween(String value1, String value2) {
            addCriterion("LXRNAME not between", value1, value2, "lxrname");
            return (Criteria) this;
        }

        public Criteria andLxrmphoneIsNull() {
            addCriterion("LXRMPHONE is null");
            return (Criteria) this;
        }

        public Criteria andLxrmphoneIsNotNull() {
            addCriterion("LXRMPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andLxrmphoneEqualTo(String value) {
            addCriterion("LXRMPHONE =", value, "lxrmphone");
            return (Criteria) this;
        }

        public Criteria andLxrmphoneNotEqualTo(String value) {
            addCriterion("LXRMPHONE <>", value, "lxrmphone");
            return (Criteria) this;
        }

        public Criteria andLxrmphoneGreaterThan(String value) {
            addCriterion("LXRMPHONE >", value, "lxrmphone");
            return (Criteria) this;
        }

        public Criteria andLxrmphoneGreaterThanOrEqualTo(String value) {
            addCriterion("LXRMPHONE >=", value, "lxrmphone");
            return (Criteria) this;
        }

        public Criteria andLxrmphoneLessThan(String value) {
            addCriterion("LXRMPHONE <", value, "lxrmphone");
            return (Criteria) this;
        }

        public Criteria andLxrmphoneLessThanOrEqualTo(String value) {
            addCriterion("LXRMPHONE <=", value, "lxrmphone");
            return (Criteria) this;
        }

        public Criteria andLxrmphoneLike(String value) {
            addCriterion("LXRMPHONE like", value, "lxrmphone");
            return (Criteria) this;
        }

        public Criteria andLxrmphoneNotLike(String value) {
            addCriterion("LXRMPHONE not like", value, "lxrmphone");
            return (Criteria) this;
        }

        public Criteria andLxrmphoneIn(List<String> values) {
            addCriterion("LXRMPHONE in", values, "lxrmphone");
            return (Criteria) this;
        }

        public Criteria andLxrmphoneNotIn(List<String> values) {
            addCriterion("LXRMPHONE not in", values, "lxrmphone");
            return (Criteria) this;
        }

        public Criteria andLxrmphoneBetween(String value1, String value2) {
            addCriterion("LXRMPHONE between", value1, value2, "lxrmphone");
            return (Criteria) this;
        }

        public Criteria andLxrmphoneNotBetween(String value1, String value2) {
            addCriterion("LXRMPHONE not between", value1, value2, "lxrmphone");
            return (Criteria) this;
        }

        public Criteria andLxrphoneIsNull() {
            addCriterion("LXRPHONE is null");
            return (Criteria) this;
        }

        public Criteria andLxrphoneIsNotNull() {
            addCriterion("LXRPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andLxrphoneEqualTo(String value) {
            addCriterion("LXRPHONE =", value, "lxrphone");
            return (Criteria) this;
        }

        public Criteria andLxrphoneNotEqualTo(String value) {
            addCriterion("LXRPHONE <>", value, "lxrphone");
            return (Criteria) this;
        }

        public Criteria andLxrphoneGreaterThan(String value) {
            addCriterion("LXRPHONE >", value, "lxrphone");
            return (Criteria) this;
        }

        public Criteria andLxrphoneGreaterThanOrEqualTo(String value) {
            addCriterion("LXRPHONE >=", value, "lxrphone");
            return (Criteria) this;
        }

        public Criteria andLxrphoneLessThan(String value) {
            addCriterion("LXRPHONE <", value, "lxrphone");
            return (Criteria) this;
        }

        public Criteria andLxrphoneLessThanOrEqualTo(String value) {
            addCriterion("LXRPHONE <=", value, "lxrphone");
            return (Criteria) this;
        }

        public Criteria andLxrphoneLike(String value) {
            addCriterion("LXRPHONE like", value, "lxrphone");
            return (Criteria) this;
        }

        public Criteria andLxrphoneNotLike(String value) {
            addCriterion("LXRPHONE not like", value, "lxrphone");
            return (Criteria) this;
        }

        public Criteria andLxrphoneIn(List<String> values) {
            addCriterion("LXRPHONE in", values, "lxrphone");
            return (Criteria) this;
        }

        public Criteria andLxrphoneNotIn(List<String> values) {
            addCriterion("LXRPHONE not in", values, "lxrphone");
            return (Criteria) this;
        }

        public Criteria andLxrphoneBetween(String value1, String value2) {
            addCriterion("LXRPHONE between", value1, value2, "lxrphone");
            return (Criteria) this;
        }

        public Criteria andLxrphoneNotBetween(String value1, String value2) {
            addCriterion("LXRPHONE not between", value1, value2, "lxrphone");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("REMARKS is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("REMARKS is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("REMARKS =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("REMARKS <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("REMARKS >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKS >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("REMARKS <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("REMARKS <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("REMARKS like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("REMARKS not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("REMARKS in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("REMARKS not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("REMARKS between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("REMARKS not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterionForJDBCDate("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterionForJDBCDate("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andRuzhuIsNull() {
            addCriterion("RUZHU is null");
            return (Criteria) this;
        }

        public Criteria andRuzhuIsNotNull() {
            addCriterion("RUZHU is not null");
            return (Criteria) this;
        }

        public Criteria andRuzhuEqualTo(BigDecimal value) {
            addCriterion("RUZHU =", value, "ruzhu");
            return (Criteria) this;
        }

        public Criteria andRuzhuNotEqualTo(BigDecimal value) {
            addCriterion("RUZHU <>", value, "ruzhu");
            return (Criteria) this;
        }

        public Criteria andRuzhuGreaterThan(BigDecimal value) {
            addCriterion("RUZHU >", value, "ruzhu");
            return (Criteria) this;
        }

        public Criteria andRuzhuGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RUZHU >=", value, "ruzhu");
            return (Criteria) this;
        }

        public Criteria andRuzhuLessThan(BigDecimal value) {
            addCriterion("RUZHU <", value, "ruzhu");
            return (Criteria) this;
        }

        public Criteria andRuzhuLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RUZHU <=", value, "ruzhu");
            return (Criteria) this;
        }

        public Criteria andRuzhuIn(List<BigDecimal> values) {
            addCriterion("RUZHU in", values, "ruzhu");
            return (Criteria) this;
        }

        public Criteria andRuzhuNotIn(List<BigDecimal> values) {
            addCriterion("RUZHU not in", values, "ruzhu");
            return (Criteria) this;
        }

        public Criteria andRuzhuBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RUZHU between", value1, value2, "ruzhu");
            return (Criteria) this;
        }

        public Criteria andRuzhuNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RUZHU not between", value1, value2, "ruzhu");
            return (Criteria) this;
        }

        public Criteria andRzdateIsNull() {
            addCriterion("RZDATE is null");
            return (Criteria) this;
        }

        public Criteria andRzdateIsNotNull() {
            addCriterion("RZDATE is not null");
            return (Criteria) this;
        }

        public Criteria andRzdateEqualTo(Date value) {
            addCriterionForJDBCDate("RZDATE =", value, "rzdate");
            return (Criteria) this;
        }

        public Criteria andRzdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("RZDATE <>", value, "rzdate");
            return (Criteria) this;
        }

        public Criteria andRzdateGreaterThan(Date value) {
            addCriterionForJDBCDate("RZDATE >", value, "rzdate");
            return (Criteria) this;
        }

        public Criteria andRzdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("RZDATE >=", value, "rzdate");
            return (Criteria) this;
        }

        public Criteria andRzdateLessThan(Date value) {
            addCriterionForJDBCDate("RZDATE <", value, "rzdate");
            return (Criteria) this;
        }

        public Criteria andRzdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("RZDATE <=", value, "rzdate");
            return (Criteria) this;
        }

        public Criteria andRzdateIn(List<Date> values) {
            addCriterionForJDBCDate("RZDATE in", values, "rzdate");
            return (Criteria) this;
        }

        public Criteria andRzdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("RZDATE not in", values, "rzdate");
            return (Criteria) this;
        }

        public Criteria andRzdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("RZDATE between", value1, value2, "rzdate");
            return (Criteria) this;
        }

        public Criteria andRzdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("RZDATE not between", value1, value2, "rzdate");
            return (Criteria) this;
        }

        public Criteria andTfdateIsNull() {
            addCriterion("TFDATE is null");
            return (Criteria) this;
        }

        public Criteria andTfdateIsNotNull() {
            addCriterion("TFDATE is not null");
            return (Criteria) this;
        }

        public Criteria andTfdateEqualTo(Date value) {
            addCriterionForJDBCDate("TFDATE =", value, "tfdate");
            return (Criteria) this;
        }

        public Criteria andTfdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("TFDATE <>", value, "tfdate");
            return (Criteria) this;
        }

        public Criteria andTfdateGreaterThan(Date value) {
            addCriterionForJDBCDate("TFDATE >", value, "tfdate");
            return (Criteria) this;
        }

        public Criteria andTfdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TFDATE >=", value, "tfdate");
            return (Criteria) this;
        }

        public Criteria andTfdateLessThan(Date value) {
            addCriterionForJDBCDate("TFDATE <", value, "tfdate");
            return (Criteria) this;
        }

        public Criteria andTfdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TFDATE <=", value, "tfdate");
            return (Criteria) this;
        }

        public Criteria andTfdateIn(List<Date> values) {
            addCriterionForJDBCDate("TFDATE in", values, "tfdate");
            return (Criteria) this;
        }

        public Criteria andTfdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("TFDATE not in", values, "tfdate");
            return (Criteria) this;
        }

        public Criteria andTfdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TFDATE between", value1, value2, "tfdate");
            return (Criteria) this;
        }

        public Criteria andTfdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TFDATE not between", value1, value2, "tfdate");
            return (Criteria) this;
        }

        public Criteria andRznumemberIsNull() {
            addCriterion("RZNUMEMBER is null");
            return (Criteria) this;
        }

        public Criteria andRznumemberIsNotNull() {
            addCriterion("RZNUMEMBER is not null");
            return (Criteria) this;
        }

        public Criteria andRznumemberEqualTo(BigDecimal value) {
            addCriterion("RZNUMEMBER =", value, "rznumember");
            return (Criteria) this;
        }

        public Criteria andRznumemberNotEqualTo(BigDecimal value) {
            addCriterion("RZNUMEMBER <>", value, "rznumember");
            return (Criteria) this;
        }

        public Criteria andRznumemberGreaterThan(BigDecimal value) {
            addCriterion("RZNUMEMBER >", value, "rznumember");
            return (Criteria) this;
        }

        public Criteria andRznumemberGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RZNUMEMBER >=", value, "rznumember");
            return (Criteria) this;
        }

        public Criteria andRznumemberLessThan(BigDecimal value) {
            addCriterion("RZNUMEMBER <", value, "rznumember");
            return (Criteria) this;
        }

        public Criteria andRznumemberLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RZNUMEMBER <=", value, "rznumember");
            return (Criteria) this;
        }

        public Criteria andRznumemberIn(List<BigDecimal> values) {
            addCriterion("RZNUMEMBER in", values, "rznumember");
            return (Criteria) this;
        }

        public Criteria andRznumemberNotIn(List<BigDecimal> values) {
            addCriterion("RZNUMEMBER not in", values, "rznumember");
            return (Criteria) this;
        }

        public Criteria andRznumemberBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RZNUMEMBER between", value1, value2, "rznumember");
            return (Criteria) this;
        }

        public Criteria andRznumemberNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RZNUMEMBER not between", value1, value2, "rznumember");
            return (Criteria) this;
        }

        public Criteria andRzroomIsNull() {
            addCriterion("RZROOM is null");
            return (Criteria) this;
        }

        public Criteria andRzroomIsNotNull() {
            addCriterion("RZROOM is not null");
            return (Criteria) this;
        }

        public Criteria andRzroomEqualTo(BigDecimal value) {
            addCriterion("RZROOM =", value, "rzroom");
            return (Criteria) this;
        }

        public Criteria andRzroomNotEqualTo(BigDecimal value) {
            addCriterion("RZROOM <>", value, "rzroom");
            return (Criteria) this;
        }

        public Criteria andRzroomGreaterThan(BigDecimal value) {
            addCriterion("RZROOM >", value, "rzroom");
            return (Criteria) this;
        }

        public Criteria andRzroomGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RZROOM >=", value, "rzroom");
            return (Criteria) this;
        }

        public Criteria andRzroomLessThan(BigDecimal value) {
            addCriterion("RZROOM <", value, "rzroom");
            return (Criteria) this;
        }

        public Criteria andRzroomLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RZROOM <=", value, "rzroom");
            return (Criteria) this;
        }

        public Criteria andRzroomIn(List<BigDecimal> values) {
            addCriterion("RZROOM in", values, "rzroom");
            return (Criteria) this;
        }

        public Criteria andRzroomNotIn(List<BigDecimal> values) {
            addCriterion("RZROOM not in", values, "rzroom");
            return (Criteria) this;
        }

        public Criteria andRzroomBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RZROOM between", value1, value2, "rzroom");
            return (Criteria) this;
        }

        public Criteria andRzroomNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RZROOM not between", value1, value2, "rzroom");
            return (Criteria) this;
        }

        public Criteria andRzpriceIsNull() {
            addCriterion("RZPRICE is null");
            return (Criteria) this;
        }

        public Criteria andRzpriceIsNotNull() {
            addCriterion("RZPRICE is not null");
            return (Criteria) this;
        }

        public Criteria andRzpriceEqualTo(BigDecimal value) {
            addCriterion("RZPRICE =", value, "rzprice");
            return (Criteria) this;
        }

        public Criteria andRzpriceNotEqualTo(BigDecimal value) {
            addCriterion("RZPRICE <>", value, "rzprice");
            return (Criteria) this;
        }

        public Criteria andRzpriceGreaterThan(BigDecimal value) {
            addCriterion("RZPRICE >", value, "rzprice");
            return (Criteria) this;
        }

        public Criteria andRzpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RZPRICE >=", value, "rzprice");
            return (Criteria) this;
        }

        public Criteria andRzpriceLessThan(BigDecimal value) {
            addCriterion("RZPRICE <", value, "rzprice");
            return (Criteria) this;
        }

        public Criteria andRzpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RZPRICE <=", value, "rzprice");
            return (Criteria) this;
        }

        public Criteria andRzpriceIn(List<BigDecimal> values) {
            addCriterion("RZPRICE in", values, "rzprice");
            return (Criteria) this;
        }

        public Criteria andRzpriceNotIn(List<BigDecimal> values) {
            addCriterion("RZPRICE not in", values, "rzprice");
            return (Criteria) this;
        }

        public Criteria andRzpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RZPRICE between", value1, value2, "rzprice");
            return (Criteria) this;
        }

        public Criteria andRzpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RZPRICE not between", value1, value2, "rzprice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CS_RESERVE
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CS_RESERVE
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}