package com.bizwink.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RoominfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    public RoominfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSiteidIsNull() {
            addCriterion("SITEID is null");
            return (Criteria) this;
        }

        public Criteria andSiteidIsNotNull() {
            addCriterion("SITEID is not null");
            return (Criteria) this;
        }

        public Criteria andSiteidEqualTo(BigDecimal value) {
            addCriterion("SITEID =", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidNotEqualTo(BigDecimal value) {
            addCriterion("SITEID <>", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidGreaterThan(BigDecimal value) {
            addCriterion("SITEID >", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SITEID >=", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidLessThan(BigDecimal value) {
            addCriterion("SITEID <", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SITEID <=", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidIn(List<BigDecimal> values) {
            addCriterion("SITEID in", values, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidNotIn(List<BigDecimal> values) {
            addCriterion("SITEID not in", values, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SITEID between", value1, value2, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SITEID not between", value1, value2, "siteid");
            return (Criteria) this;
        }

        public Criteria andRoomNameIsNull() {
            addCriterion("ROOM_NAME is null");
            return (Criteria) this;
        }

        public Criteria andRoomNameIsNotNull() {
            addCriterion("ROOM_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andRoomNameEqualTo(String value) {
            addCriterion("ROOM_NAME =", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotEqualTo(String value) {
            addCriterion("ROOM_NAME <>", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameGreaterThan(String value) {
            addCriterion("ROOM_NAME >", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameGreaterThanOrEqualTo(String value) {
            addCriterion("ROOM_NAME >=", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLessThan(String value) {
            addCriterion("ROOM_NAME <", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLessThanOrEqualTo(String value) {
            addCriterion("ROOM_NAME <=", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLike(String value) {
            addCriterion("ROOM_NAME like", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotLike(String value) {
            addCriterion("ROOM_NAME not like", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameIn(List<String> values) {
            addCriterion("ROOM_NAME in", values, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotIn(List<String> values) {
            addCriterion("ROOM_NAME not in", values, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameBetween(String value1, String value2) {
            addCriterion("ROOM_NAME between", value1, value2, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotBetween(String value1, String value2) {
            addCriterion("ROOM_NAME not between", value1, value2, "roomName");
            return (Criteria) this;
        }

        public Criteria andCatlogCodeIsNull() {
            addCriterion("CATLOG_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCatlogCodeIsNotNull() {
            addCriterion("CATLOG_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCatlogCodeEqualTo(String value) {
            addCriterion("CATLOG_CODE =", value, "catlogCode");
            return (Criteria) this;
        }

        public Criteria andCatlogCodeNotEqualTo(String value) {
            addCriterion("CATLOG_CODE <>", value, "catlogCode");
            return (Criteria) this;
        }

        public Criteria andCatlogCodeGreaterThan(String value) {
            addCriterion("CATLOG_CODE >", value, "catlogCode");
            return (Criteria) this;
        }

        public Criteria andCatlogCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CATLOG_CODE >=", value, "catlogCode");
            return (Criteria) this;
        }

        public Criteria andCatlogCodeLessThan(String value) {
            addCriterion("CATLOG_CODE <", value, "catlogCode");
            return (Criteria) this;
        }

        public Criteria andCatlogCodeLessThanOrEqualTo(String value) {
            addCriterion("CATLOG_CODE <=", value, "catlogCode");
            return (Criteria) this;
        }

        public Criteria andCatlogCodeLike(String value) {
            addCriterion("CATLOG_CODE like", value, "catlogCode");
            return (Criteria) this;
        }

        public Criteria andCatlogCodeNotLike(String value) {
            addCriterion("CATLOG_CODE not like", value, "catlogCode");
            return (Criteria) this;
        }

        public Criteria andCatlogCodeIn(List<String> values) {
            addCriterion("CATLOG_CODE in", values, "catlogCode");
            return (Criteria) this;
        }

        public Criteria andCatlogCodeNotIn(List<String> values) {
            addCriterion("CATLOG_CODE not in", values, "catlogCode");
            return (Criteria) this;
        }

        public Criteria andCatlogCodeBetween(String value1, String value2) {
            addCriterion("CATLOG_CODE between", value1, value2, "catlogCode");
            return (Criteria) this;
        }

        public Criteria andCatlogCodeNotBetween(String value1, String value2) {
            addCriterion("CATLOG_CODE not between", value1, value2, "catlogCode");
            return (Criteria) this;
        }

        public Criteria andRoomTypeIsNull() {
            addCriterion("ROOM_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andRoomTypeIsNotNull() {
            addCriterion("ROOM_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRoomTypeEqualTo(BigDecimal value) {
            addCriterion("ROOM_TYPE =", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNotEqualTo(BigDecimal value) {
            addCriterion("ROOM_TYPE <>", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeGreaterThan(BigDecimal value) {
            addCriterion("ROOM_TYPE >", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ROOM_TYPE >=", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeLessThan(BigDecimal value) {
            addCriterion("ROOM_TYPE <", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ROOM_TYPE <=", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeIn(List<BigDecimal> values) {
            addCriterion("ROOM_TYPE in", values, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNotIn(List<BigDecimal> values) {
            addCriterion("ROOM_TYPE not in", values, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ROOM_TYPE between", value1, value2, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ROOM_TYPE not between", value1, value2, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomNumIsNull() {
            addCriterion("ROOM_NUM is null");
            return (Criteria) this;
        }

        public Criteria andRoomNumIsNotNull() {
            addCriterion("ROOM_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andRoomNumEqualTo(BigDecimal value) {
            addCriterion("ROOM_NUM =", value, "roomNum");
            return (Criteria) this;
        }

        public Criteria andRoomNumNotEqualTo(BigDecimal value) {
            addCriterion("ROOM_NUM <>", value, "roomNum");
            return (Criteria) this;
        }

        public Criteria andRoomNumGreaterThan(BigDecimal value) {
            addCriterion("ROOM_NUM >", value, "roomNum");
            return (Criteria) this;
        }

        public Criteria andRoomNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ROOM_NUM >=", value, "roomNum");
            return (Criteria) this;
        }

        public Criteria andRoomNumLessThan(BigDecimal value) {
            addCriterion("ROOM_NUM <", value, "roomNum");
            return (Criteria) this;
        }

        public Criteria andRoomNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ROOM_NUM <=", value, "roomNum");
            return (Criteria) this;
        }

        public Criteria andRoomNumIn(List<BigDecimal> values) {
            addCriterion("ROOM_NUM in", values, "roomNum");
            return (Criteria) this;
        }

        public Criteria andRoomNumNotIn(List<BigDecimal> values) {
            addCriterion("ROOM_NUM not in", values, "roomNum");
            return (Criteria) this;
        }

        public Criteria andRoomNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ROOM_NUM between", value1, value2, "roomNum");
            return (Criteria) this;
        }

        public Criteria andRoomNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ROOM_NUM not between", value1, value2, "roomNum");
            return (Criteria) this;
        }

        public Criteria andRoomWayIsNull() {
            addCriterion("ROOM_WAY is null");
            return (Criteria) this;
        }

        public Criteria andRoomWayIsNotNull() {
            addCriterion("ROOM_WAY is not null");
            return (Criteria) this;
        }

        public Criteria andRoomWayEqualTo(BigDecimal value) {
            addCriterion("ROOM_WAY =", value, "roomWay");
            return (Criteria) this;
        }

        public Criteria andRoomWayNotEqualTo(BigDecimal value) {
            addCriterion("ROOM_WAY <>", value, "roomWay");
            return (Criteria) this;
        }

        public Criteria andRoomWayGreaterThan(BigDecimal value) {
            addCriterion("ROOM_WAY >", value, "roomWay");
            return (Criteria) this;
        }

        public Criteria andRoomWayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ROOM_WAY >=", value, "roomWay");
            return (Criteria) this;
        }

        public Criteria andRoomWayLessThan(BigDecimal value) {
            addCriterion("ROOM_WAY <", value, "roomWay");
            return (Criteria) this;
        }

        public Criteria andRoomWayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ROOM_WAY <=", value, "roomWay");
            return (Criteria) this;
        }

        public Criteria andRoomWayIn(List<BigDecimal> values) {
            addCriterion("ROOM_WAY in", values, "roomWay");
            return (Criteria) this;
        }

        public Criteria andRoomWayNotIn(List<BigDecimal> values) {
            addCriterion("ROOM_WAY not in", values, "roomWay");
            return (Criteria) this;
        }

        public Criteria andRoomWayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ROOM_WAY between", value1, value2, "roomWay");
            return (Criteria) this;
        }

        public Criteria andRoomWayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ROOM_WAY not between", value1, value2, "roomWay");
            return (Criteria) this;
        }

        public Criteria andRoomSizeIsNull() {
            addCriterion("ROOM_SIZE is null");
            return (Criteria) this;
        }

        public Criteria andRoomSizeIsNotNull() {
            addCriterion("ROOM_SIZE is not null");
            return (Criteria) this;
        }

        public Criteria andRoomSizeEqualTo(BigDecimal value) {
            addCriterion("ROOM_SIZE =", value, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeNotEqualTo(BigDecimal value) {
            addCriterion("ROOM_SIZE <>", value, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeGreaterThan(BigDecimal value) {
            addCriterion("ROOM_SIZE >", value, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ROOM_SIZE >=", value, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeLessThan(BigDecimal value) {
            addCriterion("ROOM_SIZE <", value, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ROOM_SIZE <=", value, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeIn(List<BigDecimal> values) {
            addCriterion("ROOM_SIZE in", values, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeNotIn(List<BigDecimal> values) {
            addCriterion("ROOM_SIZE not in", values, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ROOM_SIZE between", value1, value2, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ROOM_SIZE not between", value1, value2, "roomSize");
            return (Criteria) this;
        }

        public Criteria andInitPriceIsNull() {
            addCriterion("INIT_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andInitPriceIsNotNull() {
            addCriterion("INIT_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andInitPriceEqualTo(BigDecimal value) {
            addCriterion("INIT_PRICE =", value, "initPrice");
            return (Criteria) this;
        }

        public Criteria andInitPriceNotEqualTo(BigDecimal value) {
            addCriterion("INIT_PRICE <>", value, "initPrice");
            return (Criteria) this;
        }

        public Criteria andInitPriceGreaterThan(BigDecimal value) {
            addCriterion("INIT_PRICE >", value, "initPrice");
            return (Criteria) this;
        }

        public Criteria andInitPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INIT_PRICE >=", value, "initPrice");
            return (Criteria) this;
        }

        public Criteria andInitPriceLessThan(BigDecimal value) {
            addCriterion("INIT_PRICE <", value, "initPrice");
            return (Criteria) this;
        }

        public Criteria andInitPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INIT_PRICE <=", value, "initPrice");
            return (Criteria) this;
        }

        public Criteria andInitPriceIn(List<BigDecimal> values) {
            addCriterion("INIT_PRICE in", values, "initPrice");
            return (Criteria) this;
        }

        public Criteria andInitPriceNotIn(List<BigDecimal> values) {
            addCriterion("INIT_PRICE not in", values, "initPrice");
            return (Criteria) this;
        }

        public Criteria andInitPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INIT_PRICE between", value1, value2, "initPrice");
            return (Criteria) this;
        }

        public Criteria andInitPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INIT_PRICE not between", value1, value2, "initPrice");
            return (Criteria) this;
        }

        public Criteria andBedNumIsNull() {
            addCriterion("BED_NUM is null");
            return (Criteria) this;
        }

        public Criteria andBedNumIsNotNull() {
            addCriterion("BED_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andBedNumEqualTo(BigDecimal value) {
            addCriterion("BED_NUM =", value, "bedNum");
            return (Criteria) this;
        }

        public Criteria andBedNumNotEqualTo(BigDecimal value) {
            addCriterion("BED_NUM <>", value, "bedNum");
            return (Criteria) this;
        }

        public Criteria andBedNumGreaterThan(BigDecimal value) {
            addCriterion("BED_NUM >", value, "bedNum");
            return (Criteria) this;
        }

        public Criteria andBedNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BED_NUM >=", value, "bedNum");
            return (Criteria) this;
        }

        public Criteria andBedNumLessThan(BigDecimal value) {
            addCriterion("BED_NUM <", value, "bedNum");
            return (Criteria) this;
        }

        public Criteria andBedNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BED_NUM <=", value, "bedNum");
            return (Criteria) this;
        }

        public Criteria andBedNumIn(List<BigDecimal> values) {
            addCriterion("BED_NUM in", values, "bedNum");
            return (Criteria) this;
        }

        public Criteria andBedNumNotIn(List<BigDecimal> values) {
            addCriterion("BED_NUM not in", values, "bedNum");
            return (Criteria) this;
        }

        public Criteria andBedNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BED_NUM between", value1, value2, "bedNum");
            return (Criteria) this;
        }

        public Criteria andBedNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BED_NUM not between", value1, value2, "bedNum");
            return (Criteria) this;
        }

        public Criteria andBedTypeIsNull() {
            addCriterion("BED_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBedTypeIsNotNull() {
            addCriterion("BED_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBedTypeEqualTo(BigDecimal value) {
            addCriterion("BED_TYPE =", value, "bedType");
            return (Criteria) this;
        }

        public Criteria andBedTypeNotEqualTo(BigDecimal value) {
            addCriterion("BED_TYPE <>", value, "bedType");
            return (Criteria) this;
        }

        public Criteria andBedTypeGreaterThan(BigDecimal value) {
            addCriterion("BED_TYPE >", value, "bedType");
            return (Criteria) this;
        }

        public Criteria andBedTypeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BED_TYPE >=", value, "bedType");
            return (Criteria) this;
        }

        public Criteria andBedTypeLessThan(BigDecimal value) {
            addCriterion("BED_TYPE <", value, "bedType");
            return (Criteria) this;
        }

        public Criteria andBedTypeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BED_TYPE <=", value, "bedType");
            return (Criteria) this;
        }

        public Criteria andBedTypeIn(List<BigDecimal> values) {
            addCriterion("BED_TYPE in", values, "bedType");
            return (Criteria) this;
        }

        public Criteria andBedTypeNotIn(List<BigDecimal> values) {
            addCriterion("BED_TYPE not in", values, "bedType");
            return (Criteria) this;
        }

        public Criteria andBedTypeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BED_TYPE between", value1, value2, "bedType");
            return (Criteria) this;
        }

        public Criteria andBedTypeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BED_TYPE not between", value1, value2, "bedType");
            return (Criteria) this;
        }

        public Criteria andFloorIsNull() {
            addCriterion("FLOOR is null");
            return (Criteria) this;
        }

        public Criteria andFloorIsNotNull() {
            addCriterion("FLOOR is not null");
            return (Criteria) this;
        }

        public Criteria andFloorEqualTo(String value) {
            addCriterion("FLOOR =", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotEqualTo(String value) {
            addCriterion("FLOOR <>", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorGreaterThan(String value) {
            addCriterion("FLOOR >", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorGreaterThanOrEqualTo(String value) {
            addCriterion("FLOOR >=", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorLessThan(String value) {
            addCriterion("FLOOR <", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorLessThanOrEqualTo(String value) {
            addCriterion("FLOOR <=", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorLike(String value) {
            addCriterion("FLOOR like", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotLike(String value) {
            addCriterion("FLOOR not like", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorIn(List<String> values) {
            addCriterion("FLOOR in", values, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotIn(List<String> values) {
            addCriterion("FLOOR not in", values, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorBetween(String value1, String value2) {
            addCriterion("FLOOR between", value1, value2, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotBetween(String value1, String value2) {
            addCriterion("FLOOR not between", value1, value2, "floor");
            return (Criteria) this;
        }

        public Criteria andToiletIsNull() {
            addCriterion("TOILET is null");
            return (Criteria) this;
        }

        public Criteria andToiletIsNotNull() {
            addCriterion("TOILET is not null");
            return (Criteria) this;
        }

        public Criteria andToiletEqualTo(BigDecimal value) {
            addCriterion("TOILET =", value, "toilet");
            return (Criteria) this;
        }

        public Criteria andToiletNotEqualTo(BigDecimal value) {
            addCriterion("TOILET <>", value, "toilet");
            return (Criteria) this;
        }

        public Criteria andToiletGreaterThan(BigDecimal value) {
            addCriterion("TOILET >", value, "toilet");
            return (Criteria) this;
        }

        public Criteria andToiletGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOILET >=", value, "toilet");
            return (Criteria) this;
        }

        public Criteria andToiletLessThan(BigDecimal value) {
            addCriterion("TOILET <", value, "toilet");
            return (Criteria) this;
        }

        public Criteria andToiletLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOILET <=", value, "toilet");
            return (Criteria) this;
        }

        public Criteria andToiletIn(List<BigDecimal> values) {
            addCriterion("TOILET in", values, "toilet");
            return (Criteria) this;
        }

        public Criteria andToiletNotIn(List<BigDecimal> values) {
            addCriterion("TOILET not in", values, "toilet");
            return (Criteria) this;
        }

        public Criteria andToiletBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOILET between", value1, value2, "toilet");
            return (Criteria) this;
        }

        public Criteria andToiletNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOILET not between", value1, value2, "toilet");
            return (Criteria) this;
        }

        public Criteria andTvIsNull() {
            addCriterion("TV is null");
            return (Criteria) this;
        }

        public Criteria andTvIsNotNull() {
            addCriterion("TV is not null");
            return (Criteria) this;
        }

        public Criteria andTvEqualTo(String value) {
            addCriterion("TV =", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvNotEqualTo(String value) {
            addCriterion("TV <>", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvGreaterThan(String value) {
            addCriterion("TV >", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvGreaterThanOrEqualTo(String value) {
            addCriterion("TV >=", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvLessThan(String value) {
            addCriterion("TV <", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvLessThanOrEqualTo(String value) {
            addCriterion("TV <=", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvLike(String value) {
            addCriterion("TV like", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvNotLike(String value) {
            addCriterion("TV not like", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvIn(List<String> values) {
            addCriterion("TV in", values, "tv");
            return (Criteria) this;
        }

        public Criteria andTvNotIn(List<String> values) {
            addCriterion("TV not in", values, "tv");
            return (Criteria) this;
        }

        public Criteria andTvBetween(String value1, String value2) {
            addCriterion("TV between", value1, value2, "tv");
            return (Criteria) this;
        }

        public Criteria andTvNotBetween(String value1, String value2) {
            addCriterion("TV not between", value1, value2, "tv");
            return (Criteria) this;
        }

        public Criteria andAirconditionerIsNull() {
            addCriterion("AIRCONDITIONER is null");
            return (Criteria) this;
        }

        public Criteria andAirconditionerIsNotNull() {
            addCriterion("AIRCONDITIONER is not null");
            return (Criteria) this;
        }

        public Criteria andAirconditionerEqualTo(String value) {
            addCriterion("AIRCONDITIONER =", value, "airconditioner");
            return (Criteria) this;
        }

        public Criteria andAirconditionerNotEqualTo(String value) {
            addCriterion("AIRCONDITIONER <>", value, "airconditioner");
            return (Criteria) this;
        }

        public Criteria andAirconditionerGreaterThan(String value) {
            addCriterion("AIRCONDITIONER >", value, "airconditioner");
            return (Criteria) this;
        }

        public Criteria andAirconditionerGreaterThanOrEqualTo(String value) {
            addCriterion("AIRCONDITIONER >=", value, "airconditioner");
            return (Criteria) this;
        }

        public Criteria andAirconditionerLessThan(String value) {
            addCriterion("AIRCONDITIONER <", value, "airconditioner");
            return (Criteria) this;
        }

        public Criteria andAirconditionerLessThanOrEqualTo(String value) {
            addCriterion("AIRCONDITIONER <=", value, "airconditioner");
            return (Criteria) this;
        }

        public Criteria andAirconditionerLike(String value) {
            addCriterion("AIRCONDITIONER like", value, "airconditioner");
            return (Criteria) this;
        }

        public Criteria andAirconditionerNotLike(String value) {
            addCriterion("AIRCONDITIONER not like", value, "airconditioner");
            return (Criteria) this;
        }

        public Criteria andAirconditionerIn(List<String> values) {
            addCriterion("AIRCONDITIONER in", values, "airconditioner");
            return (Criteria) this;
        }

        public Criteria andAirconditionerNotIn(List<String> values) {
            addCriterion("AIRCONDITIONER not in", values, "airconditioner");
            return (Criteria) this;
        }

        public Criteria andAirconditionerBetween(String value1, String value2) {
            addCriterion("AIRCONDITIONER between", value1, value2, "airconditioner");
            return (Criteria) this;
        }

        public Criteria andAirconditionerNotBetween(String value1, String value2) {
            addCriterion("AIRCONDITIONER not between", value1, value2, "airconditioner");
            return (Criteria) this;
        }

        public Criteria andBathroomIsNull() {
            addCriterion("BATHROOM is null");
            return (Criteria) this;
        }

        public Criteria andBathroomIsNotNull() {
            addCriterion("BATHROOM is not null");
            return (Criteria) this;
        }

        public Criteria andBathroomEqualTo(String value) {
            addCriterion("BATHROOM =", value, "bathroom");
            return (Criteria) this;
        }

        public Criteria andBathroomNotEqualTo(String value) {
            addCriterion("BATHROOM <>", value, "bathroom");
            return (Criteria) this;
        }

        public Criteria andBathroomGreaterThan(String value) {
            addCriterion("BATHROOM >", value, "bathroom");
            return (Criteria) this;
        }

        public Criteria andBathroomGreaterThanOrEqualTo(String value) {
            addCriterion("BATHROOM >=", value, "bathroom");
            return (Criteria) this;
        }

        public Criteria andBathroomLessThan(String value) {
            addCriterion("BATHROOM <", value, "bathroom");
            return (Criteria) this;
        }

        public Criteria andBathroomLessThanOrEqualTo(String value) {
            addCriterion("BATHROOM <=", value, "bathroom");
            return (Criteria) this;
        }

        public Criteria andBathroomLike(String value) {
            addCriterion("BATHROOM like", value, "bathroom");
            return (Criteria) this;
        }

        public Criteria andBathroomNotLike(String value) {
            addCriterion("BATHROOM not like", value, "bathroom");
            return (Criteria) this;
        }

        public Criteria andBathroomIn(List<String> values) {
            addCriterion("BATHROOM in", values, "bathroom");
            return (Criteria) this;
        }

        public Criteria andBathroomNotIn(List<String> values) {
            addCriterion("BATHROOM not in", values, "bathroom");
            return (Criteria) this;
        }

        public Criteria andBathroomBetween(String value1, String value2) {
            addCriterion("BATHROOM between", value1, value2, "bathroom");
            return (Criteria) this;
        }

        public Criteria andBathroomNotBetween(String value1, String value2) {
            addCriterion("BATHROOM not between", value1, value2, "bathroom");
            return (Criteria) this;
        }

        public Criteria andBedclothesIsNull() {
            addCriterion("BEDCLOTHES is null");
            return (Criteria) this;
        }

        public Criteria andBedclothesIsNotNull() {
            addCriterion("BEDCLOTHES is not null");
            return (Criteria) this;
        }

        public Criteria andBedclothesEqualTo(String value) {
            addCriterion("BEDCLOTHES =", value, "bedclothes");
            return (Criteria) this;
        }

        public Criteria andBedclothesNotEqualTo(String value) {
            addCriterion("BEDCLOTHES <>", value, "bedclothes");
            return (Criteria) this;
        }

        public Criteria andBedclothesGreaterThan(String value) {
            addCriterion("BEDCLOTHES >", value, "bedclothes");
            return (Criteria) this;
        }

        public Criteria andBedclothesGreaterThanOrEqualTo(String value) {
            addCriterion("BEDCLOTHES >=", value, "bedclothes");
            return (Criteria) this;
        }

        public Criteria andBedclothesLessThan(String value) {
            addCriterion("BEDCLOTHES <", value, "bedclothes");
            return (Criteria) this;
        }

        public Criteria andBedclothesLessThanOrEqualTo(String value) {
            addCriterion("BEDCLOTHES <=", value, "bedclothes");
            return (Criteria) this;
        }

        public Criteria andBedclothesLike(String value) {
            addCriterion("BEDCLOTHES like", value, "bedclothes");
            return (Criteria) this;
        }

        public Criteria andBedclothesNotLike(String value) {
            addCriterion("BEDCLOTHES not like", value, "bedclothes");
            return (Criteria) this;
        }

        public Criteria andBedclothesIn(List<String> values) {
            addCriterion("BEDCLOTHES in", values, "bedclothes");
            return (Criteria) this;
        }

        public Criteria andBedclothesNotIn(List<String> values) {
            addCriterion("BEDCLOTHES not in", values, "bedclothes");
            return (Criteria) this;
        }

        public Criteria andBedclothesBetween(String value1, String value2) {
            addCriterion("BEDCLOTHES between", value1, value2, "bedclothes");
            return (Criteria) this;
        }

        public Criteria andBedclothesNotBetween(String value1, String value2) {
            addCriterion("BEDCLOTHES not between", value1, value2, "bedclothes");
            return (Criteria) this;
        }

        public Criteria andAmenitiesIsNull() {
            addCriterion("AMENITIES is null");
            return (Criteria) this;
        }

        public Criteria andAmenitiesIsNotNull() {
            addCriterion("AMENITIES is not null");
            return (Criteria) this;
        }

        public Criteria andAmenitiesEqualTo(String value) {
            addCriterion("AMENITIES =", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesNotEqualTo(String value) {
            addCriterion("AMENITIES <>", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesGreaterThan(String value) {
            addCriterion("AMENITIES >", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesGreaterThanOrEqualTo(String value) {
            addCriterion("AMENITIES >=", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesLessThan(String value) {
            addCriterion("AMENITIES <", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesLessThanOrEqualTo(String value) {
            addCriterion("AMENITIES <=", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesLike(String value) {
            addCriterion("AMENITIES like", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesNotLike(String value) {
            addCriterion("AMENITIES not like", value, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesIn(List<String> values) {
            addCriterion("AMENITIES in", values, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesNotIn(List<String> values) {
            addCriterion("AMENITIES not in", values, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesBetween(String value1, String value2) {
            addCriterion("AMENITIES between", value1, value2, "amenities");
            return (Criteria) this;
        }

        public Criteria andAmenitiesNotBetween(String value1, String value2) {
            addCriterion("AMENITIES not between", value1, value2, "amenities");
            return (Criteria) this;
        }

        public Criteria andSpecialserviceIsNull() {
            addCriterion("SPECIALSERVICE is null");
            return (Criteria) this;
        }

        public Criteria andSpecialserviceIsNotNull() {
            addCriterion("SPECIALSERVICE is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialserviceEqualTo(String value) {
            addCriterion("SPECIALSERVICE =", value, "specialservice");
            return (Criteria) this;
        }

        public Criteria andSpecialserviceNotEqualTo(String value) {
            addCriterion("SPECIALSERVICE <>", value, "specialservice");
            return (Criteria) this;
        }

        public Criteria andSpecialserviceGreaterThan(String value) {
            addCriterion("SPECIALSERVICE >", value, "specialservice");
            return (Criteria) this;
        }

        public Criteria andSpecialserviceGreaterThanOrEqualTo(String value) {
            addCriterion("SPECIALSERVICE >=", value, "specialservice");
            return (Criteria) this;
        }

        public Criteria andSpecialserviceLessThan(String value) {
            addCriterion("SPECIALSERVICE <", value, "specialservice");
            return (Criteria) this;
        }

        public Criteria andSpecialserviceLessThanOrEqualTo(String value) {
            addCriterion("SPECIALSERVICE <=", value, "specialservice");
            return (Criteria) this;
        }

        public Criteria andSpecialserviceLike(String value) {
            addCriterion("SPECIALSERVICE like", value, "specialservice");
            return (Criteria) this;
        }

        public Criteria andSpecialserviceNotLike(String value) {
            addCriterion("SPECIALSERVICE not like", value, "specialservice");
            return (Criteria) this;
        }

        public Criteria andSpecialserviceIn(List<String> values) {
            addCriterion("SPECIALSERVICE in", values, "specialservice");
            return (Criteria) this;
        }

        public Criteria andSpecialserviceNotIn(List<String> values) {
            addCriterion("SPECIALSERVICE not in", values, "specialservice");
            return (Criteria) this;
        }

        public Criteria andSpecialserviceBetween(String value1, String value2) {
            addCriterion("SPECIALSERVICE between", value1, value2, "specialservice");
            return (Criteria) this;
        }

        public Criteria andSpecialserviceNotBetween(String value1, String value2) {
            addCriterion("SPECIALSERVICE not between", value1, value2, "specialservice");
            return (Criteria) this;
        }

        public Criteria andDelflagIsNull() {
            addCriterion("DELFLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelflagIsNotNull() {
            addCriterion("DELFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelflagEqualTo(BigDecimal value) {
            addCriterion("DELFLAG =", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotEqualTo(BigDecimal value) {
            addCriterion("DELFLAG <>", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagGreaterThan(BigDecimal value) {
            addCriterion("DELFLAG >", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DELFLAG >=", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagLessThan(BigDecimal value) {
            addCriterion("DELFLAG <", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DELFLAG <=", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagIn(List<BigDecimal> values) {
            addCriterion("DELFLAG in", values, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotIn(List<BigDecimal> values) {
            addCriterion("DELFLAG not in", values, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DELFLAG between", value1, value2, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DELFLAG not between", value1, value2, "delflag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CS_ROOM_INFO
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}